// client/src/app/modules/shared/file-uploader/FileUploaderComponent.tsx
import React from "react";
import "./file-uploader.component.css";
import axios from "axios";
import { BaseComponent } from "../../../components/base/BaseComponent";
import { mdDigitalEvidence } from "../../../../models/digital-evidence";
import { StaticHelper } from "../../../../shared/static-helper";
import { mdCallResponse } from "../../../../models/call-response";
import { Progress } from "antd";

export default class FileUploaderComponent extends BaseComponent {
  render() {
    this.initShorts();
    return (
      <div className="file-uploader col-md-12">
        <input
          onChange={this.fileSelectionChanged}
          type="file"
          id={this.fileInputId}
          multiple={this.p.config.multiple}
          style={{ display: "none" }}
          accept={this.p.config.formatsAllowed.join(",")}
          ref={ref => (this.fileInput = ref)}
        />
        <label htmlFor={this.fileInputId} className="btn btn-primary">
          {this.p.config.text}
        </label>
        <button
          style={{ marginLeft: "10px" }}
          onClick={this.clearButtonClicked}
          className="btn btn-info"
        >
          {this.lang.Clear}
        </button>
        <label
          style={{ paddingLeft: "5px" }}
          className="info-label text-danger"
        >
          {this.state.status}
        </label>
        <br />
        <label className="info-label">{this.state.info}</label>
        {this.state.filesToUpload
          ? this.state.filesToUpload.map((f, i) => {
              return (
                <div
                  key={i}
                  className="row nb-theme-default stylish-border stylish-row"
                >
                  <div className="col-md-7">
                    <label className="info-label">{f.fileName}</label>
                  </div>
                  <div className="col-md-5">
                    <Progress percent={f.progressBar.progress} />
                    {/* {
                                        <ProgressBarComponent {...this.props} params={{
                                            status: f.progressBar.status,
                                            displayValue: f.progressBar.displayValue,
                                            value: f.progressBar.progress
                                        }} />
                                    } */}
                    {/* <nb-progress-bar [value]="f.progressBar.progress" [status]="f.progressBar.status" [displayValue]="f.progressBar.displayValue"></nb-progress-bar> */}
                  </div>
                </div>
              );
            })
          : null}
      </div>
    );
  }

  value: mdDigitalEvidence[] = [];
  fileInputId: string = "fu" + Math.random();
  fileInput: any;
  constructor(props) {
    super(props);
    this.init();
  }

  init() {
    this.state = {
      filesToUpload: [],
      infoText: "",
      status: ""
    };
    this.setInfoText();
  }

  recievedNewChanges() {
    this.clearFiles();
    this.setInfoText();
  }

  clearButtonClicked = e => {
    e.preventDefault();
    this.clearFiles();
  };

  clearFiles() {
    this.fileInput.value = null;
    this.resetProps();
  }

  resetProps(callback?) {
    for (let i = 0; i < this.state.filesToUpload.length; i++) {
      let file = this.state.filesToUpload[i];
      if (file.progressBar.progress < 100) {
        file.cancelTokenSource.cancel("");
      }
    }
    this.updateState(
      {
        filesToUpload: []
      },
      callback
    );
    this.p.isBusyChange(false);
    this.updateValue([]);
  }

  updateValue(val) {
    this.value = val;
    this.p.valueChange(this.value);
    this.log.debug(this.value);
  }

  setInfoText() {
    this.state = {
      ...this.state,
      infoText:
        "(" +
        this.p.config.formatsAllowed.join(", ") +
        ") " +
        this.lang.SizeLimit +
        " " +
        this.p.config.maxSize +
        " MB"
    };
  }

  fileSelectionChanged = event => {
    if (!event.target.files) {
      return;
    }
    if (event.target.files.length < 1) {
      return;
    }

    this.resetProps(() => {});
    let isError = false;
    const reader = new FileReader();

    let status = this.state.status;
    for (let i = 0; i < event.target.files.length; i++) {
      let sizeInBytes = event.target.files[i].size;
      let allowedFileSizeInBytes = this.p.config.maxSize * 1024 * 1024;
      if (sizeInBytes > allowedFileSizeInBytes) {
        status = this.lang.SizeLimitExceeds;
        isError = true;
        break;
      }
      let name = event.target.files[i].name;
      let splittedName = name.split(".");
      if (splittedName.length < 2) {
        status = StaticHelper.formatString(
          this.lang.AllowFileTypesAreFormat,
          this.p.config.formatsAllowed.join(", ")
        );
        isError = true;
        break;
      }

      if (
        this.p.config.formatsAllowed.indexOf(
          "." + splittedName[splittedName.length - 1]
        ) < 0
      ) {
        status = StaticHelper.formatString(
          this.lang.AllowFileTypesAreFormat,
          this.p.config.formatsAllowed.join(", ")
        );
        isError = true;
        break;
      }
    }
    if (status != this.state.status) {
      this.updateState({
        status: status
      });
    }

    if (isError) {
      this.updateState({
        fileInput: ""
      });
      return;
    }

    if (this.p.config.uploadEndpoint == null) {
      return;
    }

    if (this.p.config.uploadEndpoint.length < 1) {
      return;
    }

    this.p.isBusyChange(true);
    let filesToUpload = [];
    for (let i = 0; i < event.target.files.length; i++) {
      const fd = new FormData();
      fd.append("files", event.target.files[i]);
      const CancelToken = axios.CancelToken;
      const source = CancelToken.source();
      this.postFile(fd, i, source);
      filesToUpload.push({
        progressBar: {
          progress: 0,
          status: "info",
          displayValue: true
        },
        fileName: event.target.files[i].name,
        cancelTokenSource: source
      });
      this.updateState({
        filesToUpload: filesToUpload
      });
    }
  };

  postFile(fd, i, cancelTokenSource) {
    return this.http
      .postFile(
        this.p.config.uploadEndpoint,
        fd,
        event => {
          let newProgress = Math.round(
            (event["loaded"] / event["total"]) * 100
          );
          if (
            Math.round(this.state.filesToUpload[i].progressBar.progress) !==
            newProgress
          ) {
            let filesToUpload = this.state.filesToUpload;
            filesToUpload[i].progressBar.progress = newProgress;
            this.updateState({
              filesToUpload: filesToUpload
            });
          }
        },
        {
          cancelToken: cancelTokenSource.token
        }
      )
      .then((res: mdCallResponse) => {
        let filesToUpload = this.state.filesToUpload;
        filesToUpload[i].progressBar.progress = 100;
        this.p.isBusyChange(false);
        if (res.extras) {
          if (res.extras.de) {
            this.updateValue(this.value.concat(res.extras.de));
          }
        }
        this.updateState({
          filesToUpload: filesToUpload,
          status: res.isSuccess
            ? this.state.status
            : this.lang.SomethingWentWrongTryAgainLater
        });
      })
      .catch(error => {
        this.p.isBusyChange(false);
        this.log.info(error);
        this.updateState({
          status: this.lang.SomethingWentWrongTryAgainLater
        });
      });
  }
}

// client/src/modules/file-uploader/file-uploader.component.ts
import { Component, Input, Output, SimpleChanges, ViewChild } from '@angular/core';
import { Injectable } from '@angular/core';
import { Router } from '@angular/router';
import { LanguageBase } from 'src/shared/language';
import { GlobalsService } from 'src/services/globals.service';
import { FormBuilder, FormGroup } from '@angular/forms';
import * as $ from 'jquery';
import { EventEmitter } from '@angular/core';
import { mdFileUploaderConfig } from './file-uploader-config';
import { StaticHelper } from 'src/shared/static-helper';
import { areAllEquivalent } from '@angular/compiler/src/output/output_ast';
import { HttpClientService } from 'src/services/http-client.service';
import { HttpEvent, HttpEventType } from '@angular/common/http';
import { LoggerService } from 'src/services/logger.service';
import { mdCallResponse } from 'src/models/call-response';
import { mdDigitalEvidence } from 'src/models/digital-evidence';

declare var $;

@Component({
    selector: 'file-uploader',
    templateUrl: './file-uploader.component.html',
    styleUrls: ['./file-uploader.component.css']
})

export class FileUploaderComponent {

    @ViewChild("fileInput") fileInput;
    @Input() config: mdFileUploaderConfig;
    @Input() reset: boolean;
    @Input() isBusy: boolean;
    @Output() isBusyChange = new EventEmitter<any>();
    @Output() valueChange = new EventEmitter<any>();
    value: mdDigitalEvidence[] = [];
    infoText: string;
    fileInputId: string;
    status: string = '';
    selectedFileName: string;
    filesToUpload: any[] = [];

    constructor(
        private formBuilder: FormBuilder,
        public globals: GlobalsService,
        public https: HttpClientService,
        public log: LoggerService,
    ) {
        this.config = new mdFileUploaderConfig();
        this.config.text = this.globals.lang.SelectFile
        this.fileInputId = 'fu' + Math.random();
        this.setInfoText();
    }

    ngOnChanges(changes: SimpleChanges) {
        if (changes.config) {
            if (changes.config.currentValue != null) {
                this.config.setConfig(changes.config.currentValue);
            }
        }
        
        if (changes.reset) {
            this.reset = changes.reset.currentValue;
            if (this.reset) {
                this.clearFiles();
            }
        }

        this.setInfoText();
    }

    clearButtonClicked()
    {
        this.clearFiles();
    }

    clearFiles() {
        this.fileInput.nativeElement.value = '';
        this.resetProps();
    }

    resetProps()
    {
        this.selectedFileName = '';
        for(let i = 0; i < this.filesToUpload.length; i++)
        {
            this.filesToUpload[i].httpRequest.unsubscribe();
        }
        this.filesToUpload = [];
        this.isBusyChange.emit(false);
        this.updateValue([]);
    }

    updateValue(val)
    {
        this.value = val;
        this.valueChange.emit(this.value);
        this.log.debug(this.value);
    }

    setInfoText() {
        this.infoText = '(' + this.config.formatsAllowed.join(', ') + ') ' + this.globals.lang.SizeLimit + ' ' + this.config.maxSize + ' MB'
    }

    ngOnInit() {
    }

    get fi() { return this.fileInput.nativeElement; }

    fileSelectionChanged(event) {
        if (!event.target.files) {
            return;
        }
        if (event.target.files.length < 1) {
            return;
        }
        
        this.resetProps();
        let isError = false; const reader = new FileReader();

        for (let i = 0; i < event.target.files.length; i++) {
            let sizeInBytes = event.target.files[i].size;
            let allowedFileSizeInBytes = this.config.maxSize * 1024 * 1024;
            if (sizeInBytes > allowedFileSizeInBytes) {
                this.status = this.globals.lang.SizeLimitExceeds;
                isError = true;
                break;
            }
            let name = event.target.files[i].name;
            let splittedName = name.split('.');
            if (splittedName.length < 2) {
                this.status = StaticHelper.formatString(this.globals.lang.AllowFileTypesAreFormat, this.config.formatsAllowed.join(', '));
                isError = true;
                break;
            }

            if (this.config.formatsAllowed.indexOf('.' + splittedName[splittedName.length - 1]) < 0) {
                this.status = StaticHelper.formatString(this.globals.lang.AllowFileTypesAreFormat, this.config.formatsAllowed.join(', '));
                isError = true;
                break;
            }
        }

        if (isError) {
            this.fileInput.nativeElement.value = '';
            return;
        }

        if (this.config.uploadEndpoint == null) {
            return;
        }

        if (this.config.uploadEndpoint.length < 1) {
            return;
        }

        this.isBusyChange.emit(true);
        for (let i = 0; i < event.target.files.length; i++) {
            this.filesToUpload.push({
                progressBar: {
                    progress: 0,
                    status: 'info',
                    displayValue: true,
                },
                fileName: event.target.files[i].name,
            });
            const fd = new FormData();
            fd.append('files', <File>event.target.files[i]);
            this.filesToUpload[i].httpRequest = this.https.postFile(this.config.uploadEndpoint, fd).subscribe((event: HttpEvent<any>) => {
                switch (event.type) {
                    case HttpEventType.Sent:
                        this.filesToUpload[i].progressBar.progress = 0;
                        break;
                    case HttpEventType.Response:
                        this.filesToUpload[i].progressBar.progress = 100;
                        this.isBusyChange.emit(false);
                        let res: mdCallResponse = event.body as mdCallResponse;
                        if (!res.isSuccess) {
                            this.status = this.globals.lang.SomethingWentWrongTryAgainLater;
                            return;
                        }
                        if (res.extras) {
                            if (res.extras.de) {
                                this.updateValue(this.value.concat(res.extras.de));
                            }
                        }
                        break;
                    case 1: {
                        let newProgress = Math.round(event['loaded'] / event['total'] * 100);
                        if (Math.round(this.filesToUpload[i].progressBar.progress) !== newProgress) {
                            this.filesToUpload[i].progressBar.progress = newProgress;
                        }
                        break;
                    }
                }
            }, error => {
                this.isBusyChange.emit(false);
                this.log.info(error);
                this.status = this.globals.lang.SomethingWentWrongTryAgainLater;
            });
        }
        // setTimeout(this.updateProgress, 100);
    }

}

<div class="file-uploader col-md-12">
    <input #fileInput (change)="fileSelectionChanged($event)" type="file" [id]="fileInputId" [multiple]="config.multiple"
        style="display:none;" [accept]="config.formatsAllowed.join(',')" />
    <label [for]="fileInputId" class="btn btn-primary" [innerHTML]="config.text"></label>
    <button style="margin-left:10px;" (click)="clearButtonClicked()" class="btn btn-info" [innerHTML]="globals.lang.Clear"></button>
    <label style="padding-left: 5px;" class="info-label text-danger" [innerHTML]="status"></label>
    <br>
    <label class="info-label" [innerHTML]="infoText"></label>
    <div class="row nb-theme-default stylish-border stylish-row" *ngFor="let f of filesToUpload">
        <div class="col-md-7">
            <label class="info-label" [innerHTML]="f.fileName"></label>
        </div>
        <div class="col-md-5">
            <nb-progress-bar [value]="f.progressBar.progress" [status]="f.progressBar.status" [displayValue]="f.progressBar.displayValue"></nb-progress-bar>
        </div>
    </div>
</div>
