// client/src/app/order/order.component.ts
import { Component, OnInit, Input, EventEmitter, SimpleChanges } from '@angular/core';
import { LoggerService } from 'src/services/logger.service';
import { LanguageBase } from 'src/shared/language';
import { GlobalsService } from 'src/services/globals.service';
import { FormGroup, FormBuilder } from '@angular/forms';
import { mdOrder } from 'src/models/order';
import { mdCallResponse } from 'src/models/call-response';
import { HttpClientService } from 'src/services/http-client.service';
import { SpinnerService } from 'src/services/spinner.service';
import { StaticHelper } from 'src/shared/static-helper';
import { Constants } from 'src/shared/constants';

@Component({
    selector: 'app-trade-order',
    templateUrl: './order.component.html',
    styleUrls: []
})

export class OrderComponent implements OnInit {

    @Input() currencyPair: any;
    lang: LanguageBase;
    buyBalance: string;
    sellBalance: string;
    availableBalance: number;
    bform: FormGroup;
    sform: FormGroup;
    model: mdOrder;
    sellTotalAmount: string;
    alertClass: string;
    alertMessage: string;
    displayAlert: boolean;
    limitBuyTotalAmount: string;
    limitBuyGrossAmount: string;
    limitBuyFeeAmount: string;
    limitSellTotalAmount: string;
    limitSellGrossAmount: string;
    limitSellFeeAmount: string;
    priceStep: number;
    amountStep: number;
    submitted: boolean;
    constants: Constants;
    constructor(private log: LoggerService,
        public globals: GlobalsService,
        private formBuilder: FormBuilder,
        private http: HttpClientService,
        private spinner: SpinnerService) {

    }

    ngOnInit() {
        this.constants = this.globals.constants;
        this.displayAlert = false;
        this.alertClass = "";
        this.alertMessage = "";
        this.lang = this.globals.lang;
        this.availableBalance;
        this.model = new mdOrder(true);
        this.bform = this.formBuilder.group({
            price: [
                this.model.price,
                null
            ],
            amount: [
                this.model.amount,
            ],
        });
        this.sform = this.formBuilder.group({
            price: [
                this.model.price,
                null
            ],
            amount: [
                this.model.amount,
            ],
        });
    }

    get bf() { return this.bform.controls; }

    get sf() { return this.sform.controls; }

    ngOnChanges(changes: SimpleChanges) {
        this.currencyPair = changes.currencyPair.currentValue;
        this.spinner.show();
        this.loadBalanceAndFee();
    }

    loadBalanceAndFee() {
        this.sellBalance = "";
        this.buyBalance = "";

        if (this.currencyPair.id) {
            let res: mdCallResponse = new mdCallResponse();
            this.http.post<mdCallResponse>(this.constants.EndPoints.PostPairDetails, this.currencyPair.id).subscribe((data) => {
                res = data;
            }, (error) => {
                this.log.debug(error);
                this.spinner.hide();
            }, () => {
                if (res.isSuccess) {
                    Object.assign(this.currencyPair, res.extras);
                    this.log.debug(this.currencyPair);
                    this.updateBalances();
                }
                this.spinner.hide();
            });
        }
    }

    updateBalances() {
        this.sellBalance = (this.currencyPair.fc_available_balance / this.constants.Float)
            .toFixed(this.currencyPair.fc_scale) + " " + this.currencyPair.fc_name;
        this.buyBalance = (this.currencyPair.tc_available_balance / this.constants.Float)
            .toFixed(this.currencyPair.tc_scale) + " " + this.currencyPair.tc_name;
        this.limitBuyFeeAmount = StaticHelper.bestScale(StaticHelper.unfloatAmount(this.currencyPair.buy_fee)) + "%";
        this.limitSellFeeAmount = StaticHelper.bestScale(StaticHelper.unfloatAmount(this.currencyPair.sell_fee)) + "%";
        this.priceStep = 1 / Math.pow(10, StaticHelper.minScale(this.currencyPair.tc_scale));
        this.amountStep = 1 / Math.pow(10, StaticHelper.minScale(this.currencyPair.fc_scale));
    }

    onSubmit(action: number) {
        //validate form locally
        let formData: mdOrder;
        if (action == this.constants.Order.Action.buy) {
            formData = this.bform.value;
        }
        else
            if (action == this.constants.Order.Action.sell) {
                formData = this.sform.value;
            }
        formData.action = action;
        formData.currencyPair = this.currencyPair.id;
        formData.type = this.constants.Order.Type.limit;
        let res: mdCallResponse = new mdCallResponse();
        this.spinner.show();
        this.http.postPromise<mdCallResponse>(this.constants.EndPoints.PostOrder, formData).then((res: mdCallResponse) => {

            this.log.debug(res);
            this.displayAlertBox(res.isSuccess, res.message);
            this.loadBalanceAndFee();
            if (action == this.constants.Order.Action.buy) {
                this.bf.amount.setValue(0);
                this.priceAmountKeyup(this.bf);
            }
            else
                if (action == this.constants.Order.Action.sell) {
                    this.sf.amount.setValue(0);
                    this.priceAmountKeyup(this.sf);
                }
            this.spinner.hide();
        }).catch((error) => {
            this.log.debug(error);
            this.spinner.hide();
        });
    }

    displayAlertBox(isSuccess: boolean, message: string) {
        if (isSuccess) {
            this.alertClass = "alert alert-success";
        }
        else {
            this.alertClass = "alert alert-danger";
        }
        if (message) {
            message = StaticHelper.bulletList(message.split("\n"));
        }
        this.alertMessage = message;
        this.displayAlert = true;
        setTimeout(() => {
            this.displayAlert = false;
        }, this.constants.ResponseMessageTimeout * 1000);
    }

    priceAmountKeyup(f) {
        let grossAmount = f.price.value * f.amount.value;
        if (f == this.bf) {
            let feeAmount = grossAmount * (StaticHelper.unfloatAmount(this.currencyPair.buy_fee) / 100);
            let totalAmount = grossAmount + feeAmount;
            this.limitBuyGrossAmount = StaticHelper.bestScale(grossAmount)
                + " " + this.currencyPair.tc_name;
            //this.limitBuyFeeAmount = feeAmount.toFixed(StaticHelper.bestScale(0));
            this.limitBuyTotalAmount = totalAmount.toFixed(StaticHelper.minScale(this.currencyPair.tc_scale)) + " " + this.currencyPair.tc_name;;
        }
        else {
            let feeAmount = grossAmount * (StaticHelper.unfloatAmount(this.currencyPair.sell_fee) / 100);
            let totalAmount = grossAmount + feeAmount;
            this.limitSellGrossAmount = StaticHelper.bestScale(grossAmount)
                + " " + this.currencyPair.tc_name;
            //this.limitSellFeeAmount = feeAmount.toFixed(StaticHelper.bestScale(0));
            this.limitSellTotalAmount = totalAmount.toFixed(StaticHelper.minScale(this.currencyPair.tc_scale)) + " " + this.currencyPair.tc_name;;
        }
    }

}

<div class="row">
    <div class=" col-md-12">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#star-tab">{{lang.Limit}}</a></li>
            <!-- <li><a data-toggle="tab" href="#usd-tab">{{lang.Market}}</a></li> -->
            <!-- <li><a data-toggle="tab" href="#eur-tab">Stop-Loss</a></li> -->
        </ul>
        <div class="tab-content">
            <div id="star-tab" class="tab-pane fade in active">
                <div class="row">
                    <div class="col-md-6">
                        <div class="tabs_das">
                            <h3>{{lang.AvailableBalance}}<span [innerHTML]="buyBalance"></span></h3>
                            <form [formGroup]="bform" (ngSubmit)="onSubmit(constants.Order.Action.buy)">
                                <div class="input_elment">
                                    <label [innerHTML]="lang.Price"></label>
                                    <input (input)="priceAmountKeyup(bf)" type="number" min="0" class="form-control"
                                        [step]="priceStep" numberd-only placeholder="{{currencyPair.tc_name}}"
                                        formControlName="price" [ngClass]="{ 'is-invalid': submitted && bf.price.errors }" />
                                </div>
                                <div class="input_elment">
                                    <label [innerHTML]="lang.Amount"></label>
                                    <input (input)=priceAmountKeyup(bf) type="number" [step]="amountStep" min="0" class="form-control"
                                        numberd-only placeholder="{{currencyPair.fc_name}}" formControlName="amount"
                                        [ngClass]="{ 'is-invalid': submitted && bf.amount.errors }" />
                                </div>
                                <div class="vin">
                                    <span>25%</span>&nbsp;<span>50%</span>&nbsp;<span>75%</span>&nbsp;<span>100%</span>
                                </div>
                                <div class="to_amount">
                                    <label [innerHTML]="lang.Gross"></label>
                                    <span [innerHTML]="limitBuyGrossAmount"></span>
                                </div>
                                <div class="to_amount">
                                    <label [innerHTML]="lang.Fee"></label>
                                    <span [innerHTML]="limitBuyFeeAmount"></span>
                                </div>
                                <div class="to_amount">
                                    <label [innerHTML]="lang.Total"></label>
                                    <span [innerHTML]="limitBuyTotalAmount"></span>
                                </div>
                                <button class="buy_bt">
                                    <img src="assets/images/buy-icon.png" style="width:20px; margin-right:10px;"
                                        alt="lang.Buy">
                                    <span [innerHTML]="lang.Buy"></span>
                                </button>
                            </form>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="tabs_das">
                            <h3>{{lang.AvailableBalance}}<span [innerHTML]="sellBalance"></span></h3>
                            <form [formGroup]="sform" (ngSubmit)="onSubmit(constants.Order.Action.sell)">
                                <div class="input_elment">
                                    <label [innerHTML]="lang.Price"></label>
                                    <input (input)=priceAmountKeyup(sf) type="number" min="0" [step]="priceStep" class="form-control"
                                        numberd-only placeholder="{{currencyPair.tc_name}}" formControlName="price"
                                        [ngClass]="{ 'is-invalid': submitted && sf.price.errors }" />
                                </div>
                                <div class="input_elment">
                                    <label [innerHTML]="lang.Amount"></label>
                                    <input (input)=priceAmountKeyup(sf) type="number" [step]="amountStep" min="0" class="form-control"
                                        numberd-only placeholder="{{currencyPair.fc_name}}" formControlName="amount"
                                        [ngClass]="{ 'is-invalid': submitted && sf.amount.errors }" />
                                </div>
                                <div class="vin">
                                    <span>25%</span>&nbsp;<span>50%</span>&nbsp;<span>75%</span>&nbsp;<span>100%</span>
                                </div>
                                <div class="to_amount">
                                    <label [innerHTML]="lang.Gross"></label>
                                    <span [innerHTML]="limitSellGrossAmount"></span>
                                </div>
                                <div class="to_amount">
                                    <label [innerHTML]="lang.Fee"></label>
                                    <span [innerHTML]="limitSellFeeAmount"></span>
                                </div>
                                <div class="to_amount">
                                    <label [innerHTML]="lang.Total"></label>
                                    <span [innerHTML]="limitSellTotalAmount"></span>
                                </div>
                                <button class="buy_bt bt_dark"><img src="assets/images/sell-icon.png" style="width:20px; margin-right:5px;"
                                        alt="lang.Sell"> <span [innerHTML]="lang.Sell"></span></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div id="usd-tab" class="tab-pane fade ">
                <div class="row">
                    <div class="col-md-6">
                        <div class="tabs_das">
                            <h3>Buy APPC <span>0.000002019 BTC</span></h3>
                            <form>
                                <div class="input_elment">
                                    <label>Price </label>
                                    <select name="">
                                    </select>
                                </div>
                                <div class="input_elment">
                                    <label>Amount </label>
                                    <input name="" type="text" value="APPC">
                                </div>
                                <div class="vin"> <span>25%</span> <span>50%</span> <span>75%</span> <span>100%</span></div>
                                <div class="to_amount">
                                    <label>Total</label>
                                    <span>0.0000000BTC</span> </div>
                                <button type="button" class="buy_bt bt_dark"><img src="assets/images/sell-icon.png"
                                        style="width:20px; margin-right:5px;" alt="img"> Buy</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div id="eur-tab" class="tab-pane fade in">
                <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table-responsive">
                    <tr>
                        <td align="center" valign="middle" class="white-txt"><i class="fa fa-star" aria-hidden="true"></i>
                            BTCUSD</td>
                        <td align="center" valign="middle" class="white-txt">7,486.2</td>
                        <td align="center" valign="middle" class="white-txt">-1.5%</td>
                        <td align="center" valign="middle" class="white-txt">7,599.7</td>
                        <td align="center" valign="middle" class="white-txt">7,413.8</td>
                        <td align="center" valign="middle" class="white-txt">135,942,900 USD</td>
                    </tr>
                    <tr>
                        <td align="center" valign="middle" class="white-txt"><i class="fa fa-star" aria-hidden="true"></i>
                            BTCUSD</td>
                        <td align="center" valign="middle" class="white-txt">988.82</td>
                        <td align="center" valign="middle" class="white-txt">-3.6%</td>
                        <td align="center" valign="middle" class="white-txt">1,030.0</td>
                        <td align="center" valign="middle" class="white-txt">982.24 </td>
                        <td align="center" valign="middle" class="white-txt">24,967,202 USD</td>
                    </tr>
                    <tr>
                        <td align="center" valign="middle" class="white-txt"><i class="fa fa-star" aria-hidden="true"></i>
                            BTCUSD</td>
                        <td align="center" valign="middle" class="white-txt">7,486.2</td>
                        <td align="center" valign="middle" class="white-txt">-1.5%</td>
                        <td align="center" valign="middle" class="white-txt">7,599.7</td>
                        <td align="center" valign="middle" class="white-txt">7,413.8</td>
                        <td align="center" valign="middle" class="white-txt">135,942,900 USD</td>
                    </tr>
                    <tr>
                        <td align="center" valign="middle" class="white-txt"><i class="fa fa-star" aria-hidden="true"></i>
                            BTCUSD</td>
                        <td align="center" valign="middle" class="white-txt">988.82</td>
                        <td align="center" valign="middle" class="white-txt">-3.6%</td>
                        <td align="center" valign="middle" class="white-txt">1,030.0</td>
                        <td align="center" valign="middle" class="white-txt">982.24 </td>
                        <td align="center" valign="middle" class="white-txt">24,967,202 USD</td>
                    </tr>
                </table>
            </div>
            <div *ngIf="displayAlert" [class]="alertClass" [innerHTML]="alertMessage"></div>
        </div>
    </div>
</div>

// client/src/app/modules/trade/OrderComponent.tsx
import * as React from "react";
import * as ValidationAttributes from "../../../shared/validation-attributes";
import NBSpinnerComponent from "../shared/spinner/NBSpinnerComponent";
import { BaseComponent } from "../../components/base/BaseComponent";
import { mdOrder } from "../../../models/order";
import { mdFormControl } from "../../../shared/form-control";
import { mdCallResponse } from "../../../models/call-response";
import { StaticHelper } from "../../../shared/static-helper";
import { Tabs, Card, Row, Form, Button, Col } from "antd";
import { OrderActions, CurrencyTypes } from "../../../enums/order";
import { mdKeyValue } from "../../../models/key-value";
const TabPane = Tabs.TabPane;

export default class OrderComponent extends BaseComponent {

  render() {
    this.initShorts();
    let cp = this.g.selectedCurrencyPair;
    let currencyTypeSource: mdKeyValue[] = [];
    if (!cp) {
      cp = {
        fc_name: '',
      };
    }
    else {
      currencyTypeSource.push(new mdKeyValue(cp.tc_name, CurrencyTypes.Base));
      currencyTypeSource.push(new mdKeyValue(cp.fc_name, CurrencyTypes.Quote));
    }
    let balance = "";
    if (this.action == OrderActions.buy && !this.isNullOrEmpty(this.state.buyBalance)) {
      balance = this.state.buyBalance
    }
    else
      if (this.action == OrderActions.sell && !this.isNullOrEmpty(this.state.sellBalance)) {
        balance = this.state.sellBalance
      }
    let amountStep = 1;
    if (this.f.amountCurrency.value == CurrencyTypes.Base) {
      amountStep = this.state.tcStep;
    }
    else if (this.f.amountCurrency.value == CurrencyTypes.Quote) {
      amountStep = this.state.fcStep;
    }
    return (
      <>
        {/* <Row>
          {
            this.colmd12( */}
        <Card className="gx-card"
          title={OrderActions[this.action] + " " + cp.fc_name}>

          <Form onSubmit={this.onSubmit} className="gx-signin-form gx-form-row0">
            {
              this.getLabelAndValueRow(this.lang.Balance + ":",
                <span className="gx-mb-2 gx-text-primary gx-font-weight-semi-bold gx-fs-lg">
                  {balance}
                </span>)
            }
            {/* <Row>
              <Col {...this.formItemLayout.labelCol} style={{ textAlign: 'right', paddingLeft: 0 }}>
                <label style={{ }}>{this.lang.Balance + ":"}</label>
              </Col>
              <Col {...this.formItemLayout.wrapperCol} style={{ textAlign: 'right', paddingRight: 0 }}>
                <p className="gx-mb-2 gx-text-primary gx-font-weight-semi-bold gx-fs-lg">
                  {balance}
                </p>
              </Col>
            </Row> */}
            {
              this.antd.numberFormItem(this.f.price, true, this.state.tcStep, 0, 9999999, this.priceAmountKeyup, this.formItemLayout)
            }
            {
              this.antd.numberWithDropDownFormItem(this.f.amount, this.f.amountCurrency, currencyTypeSource, this.priceAmountKeyup,
                true, amountStep, 0, 9999999, currencyTypeSource.length < 1, this.priceAmountKeyup, this.formItemLayout)
            }
            {
              this.getLabelAndValueRow(this.lang.Gross + ":", this.state.limitGrossAmount)
            }
            {
              this.getLabelAndValueRow(this.lang.Fee + ":", this.state.limitFeeAmount)
            }
            {
              this.getLabelAndValueRow(this.lang.Total + ":", this.state.limitTotalAmount)
            }
            {
              <Button loading={this.state.disableSubmitButton}
                type={this.action == OrderActions.buy ? "primary" : "danger"}
                htmlType="submit"
                style={{
                  backgroundColor: '#ff4d4f',
                  color: 'white'
                }}
                className="gx-w-100">
                <img src={this.action == OrderActions.buy ? "/assets/images/buy-icon.png" :
                  "/assets/images/sell-icon.png"}
                  style={{ width: '30px', marginRight: '15px' }}
                  alt={this.action == OrderActions.buy ? this.lang.Buy : this.lang.Sell} />
                <span>{this.action == OrderActions.buy ? this.lang.Buy : this.lang.Sell}</span>
              </Button>
            }
          </Form>
        </Card>
        {/* )
          }
        </Row> */}
      </>
    );
  }

  getLabelAndValueRow(label, value) {
    if (this.isNullOrEmpty(value)) {
      value = <>&nbsp;</>
    }
    return (
      <Row>
        <Col {...this.formItemLayout.labelCol} style={{ textAlign: 'right', paddingLeft: 0 }}>
          <label style={{}}>{label}</label>
        </Col>
        <Col {...this.formItemLayout.wrapperCol} style={{ textAlign: 'right', paddingRight: 0 }}>
          <p className="gx-mb-2 gx-text-primary gx-font-weight-semi-bold gx-fs-lg">
            {value}
          </p>
        </Col>
      </Row>
    );
  }

  formItemLayout = {
    labelAlign: 'right',
    labelCol: {
      xs: { span: 6 },
      sm: { span: 6 },
      md: { span: 7 },
      style: {
        // paddingLeft: 0,
        // paddingRight: 0,
        textAlign: 'right'
      }
    },
    wrapperCol: {
      xs: { span: 18 },
      sm: { span: 18 },
      md: { span: 17 },
      style: {
        paddingLeft: 0,
        paddingRight: 0,
      }
    },
  };
  model: mdOrder;
  action: OrderActions;

  constructor(props) {
    super(props);
    this.init();
  }

  resetForm = (e?) => {
    let defaultPrice = '';
    if (this.g.selectedBriefHistory) {
      defaultPrice = this.g.selectedBriefHistory.last;
    }
    let state = {
      form: {
        price: new mdFormControl(defaultPrice, "price", this.lang.Price, [
          new ValidationAttributes.RequiredValidator(this.lang.RequiredFormat),
        ]),
        amount: new mdFormControl('', "amount", this.lang.Amount, [
          new ValidationAttributes.RequiredValidator(this.lang.RequiredFormat),
        ]),
        amountCurrency: new mdFormControl(CurrencyTypes.Base, "amountCurrency"),
        showErrors: false,
      },
      showSpinner: true,
      limitGrossAmount: "",
      limitTotalAmount: "",
      limitFeeAmount: "",
      tcStep: 1,
      fcStep: 1,
      disableSubmitButton: false,
    }
    if (!e) {
      this.state = {
        ...this.state,
        ...state
      }
    }
    else {
      this.updateState(state);
    }
  }

  init = () => {
    this.action = this.p.action;
    this.resetForm();
  }

  componentWillReceiveProps(nextProps) {
    if (nextProps != this.props) {
      this.initShorts();
      if (StaticHelper.isNullOrEmpty(this.f.price.value) && this.g.selectedBriefHistory) {
        let last = this.g.selectedBriefHistory.last;
        if (last) {
          this.handleFormControlInputWithValue(this.f.price.name, last)
        }
      }
      this.updateBalances();
    }
  }

  componentWillUpdate() {
    // if (!this.g.selectedCurrencyPair) {
    //   this.recievedNewChanges(this.g.selectedCurrencyPair);
    // }
  }

  recievedNewChanges = (newCP) => {
    // this.log.debug("recievedNewChanges");
    // if (!newCP) {
    //   return;
    // }
    // let oldCP = this.currencyPair;
    // if (oldCP) {
    //   if (oldCP.id == newCP.id) {
    //     return;
    //   }
    // }
    // this.currencyPair = newCP;
    // if (this.currencyPair) {
    //   this.state = {
    //     ...this.state,
    //     showSpinner: true,
    //   }
    //   // this.loadBalanceAndFee();
    // }
  }

  updateBalances = () => {
    let cpDetails = this.p.currencyPairDetails
    let cp = this.g.selectedCurrencyPair;
    if (!cpDetails || !cp) {
      return;
    }
    let feeAmount = this.action == OrderActions.buy ? cpDetails.buy_fee : cpDetails.sell_fee;
    let sellBalance = cpDetails.fc_available_balance ? (cpDetails.fc_available_balance / this.constants.Float)
      .toFixed(cpDetails.fc_scale) : '';
    let buyBalance = cpDetails.tc_available_balance ? (cpDetails.tc_available_balance / this.constants.Float)
      .toFixed(cpDetails.tc_scale) : '';
    this.updateState({
      sellBalance: sellBalance + " " + cp.fc_name,
      buyBalance: buyBalance + " " + cp.tc_name,
      tcStep: 1 / Math.pow(10, StaticHelper.minScale(cpDetails.tc_scale)),
      fcStep: 1 / Math.pow(10, StaticHelper.minScale(cpDetails.fc_scale)),
    })
  }

  onSubmit = (e) => {
    e.preventDefault();
    //validate form locally

    if (!this.validateForm("form")) {
      return;
    }

    let formData = this.getFormData(this.state.form) as mdOrder;
    if (this.state.form.amountCurrency.value == CurrencyTypes.Base) {
      formData.amount = formData.amount / formData.price;
    }
    formData.action = this.action;
    formData.currencyPair = this.g.selectedCurrencyPair.id;
    formData.type = this.constants.Order.Type.limit;
    this.updateState({
      disableSubmitButton: true,
    });
    this.http.post<mdCallResponse>(this.constants.EndPoints.PostOrder, formData).then((res: mdCallResponse) => {
      this.log.debug(res);
      if (res.isSuccess) {
        this.successNotification(this.lang.Success, res.message);
        this.p.onNewOrder();
        this.resetForm({});
        // this.loadBalanceAndFee();
      }
      else {
        this.errorNotification(this.lang.ErrorOccured, res.message);
      }
      this.updateState({
        disableSubmitButton: false,
      })
    }).catch((error) => {
      this.log.debug(error);
      this.updateState({
        disableSubmitButton: false,
      })
    });
  }

  priceAmountKeyup = (name, e) => {
    let cpDetails = this.p.currencyPairDetails;
    let cp = this.g.selectedCurrencyPair;
    if (!cpDetails || !cp) {
      return;
    }
    let f: any;
    f = this.state.form;
    let grossAmount = f.price.value * f.amount.value;
    if (f.amountCurrency.value == CurrencyTypes.Base) {
      grossAmount = f.amount.value;
    }
    if (!grossAmount) {
      grossAmount = 0;
    }
    if (this.action == OrderActions.buy) {
      let feeAmount = grossAmount * (StaticHelper.unfloatAmount(cpDetails.buy_fee) / 100);
      let totalAmount = grossAmount + feeAmount;
      let fee = StaticHelper.bestScale(feeAmount)
      this.updateState({
        limitFeeAmount: this.emptyNaN(fee) + " " + cp.tc_name,
        limitGrossAmount: this.emptyNaN(StaticHelper.bestScale(grossAmount)) + " " + cp.tc_name,
        limitTotalAmount: this.emptyNaN(totalAmount.toFixed(StaticHelper.minScale(cpDetails.tc_scale))) + " " + cp.tc_name,
      })
    }
    else {
      let feeAmount = grossAmount * (StaticHelper.unfloatAmount(cpDetails.sell_fee) / 100);
      let totalAmount = grossAmount + feeAmount;
      this.log.debug('gm', grossAmount);
      this.updateState({
        limitFeeAmount: this.emptyNaN(StaticHelper.bestScale(feeAmount)) + " " + cp.tc_name,
        limitGrossAmount: this.emptyNaN(StaticHelper.bestScale(grossAmount)) + " " + cp.tc_name,
        limitTotalAmount: this.emptyNaN(totalAmount.toFixed(StaticHelper.minScale(cpDetails.tc_scale))) + " " + cp.tc_name,
      })
    }
  }

}
