// client/src/modules/funding/deposit/deposit.component.ts
import { Component } from '@angular/core';
import { Injectable } from '@angular/core';
import { Router } from '@angular/router';
import { LanguageBase } from 'src/shared/language';
import { GlobalsService } from 'src/services/globals.service';
import { SearchableDropdownSettings } from 'src/modules/searchable-dropdown/searchable-dropdown-settings';
import { mdCallResponse } from 'src/models/call-response';
import { Constants } from 'src/shared/constants';
import { LoggerService } from 'src/services/logger.service';
import { HttpClientService } from 'src/services/http-client.service';
import * as EnumsFeeSlabs from 'src/enums/fee-slabs';
import * as EnumsDepositRequest from 'src/enums/deposit-requests';
import { StaticHelper } from 'src/shared/static-helper';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
import { mdDepositRequests } from 'src/models/deposit-requests';
import {
    trigger,
    state,
    style,
    animate,
    transition,
    useAnimation,
    AnimationOptions
    // ...
} from '@angular/animations';
import {
    fadeIn,
    slideOutUp,
    slideInUp,
    flipInY,
    slideOutRight,
    bounceOut,
    bounceInRight,
    bounceOutRight,
} from 'ng-animate';
import { DatePipe } from '@angular/common';
import { mdDepositRequestHisotryRequest } from 'src/models/deposit-request-history-request';
import { mdDepositRequestHistory } from 'src/models/deposit-request-history';
import { LocalDataSource } from 'ng2-smart-table';
import { ButtonCellSmartTableRendererComponent } from 'src/modules/shared/button-cell-smat-table/button-cell-smat-table.component';
import { mdButtonCellSmartTableRenderValue } from 'src/modules/shared/models/button-cell-smart-table-render-value';
import { ToasterService } from 'src/services/toaster.service';
import { mdFileUploaderConfig } from 'src/modules/file-uploader/file-uploader-config';
import { mdDepositMethods } from 'src/models/deposit-methods';
import { mdFeeSlabs } from 'src/models/fee-slabs';
import { mdDigitalEvidence } from 'src/models/digital-evidence';

@Component({
    selector: 'funding-deposit',
    templateUrl: './deposit.component.html',
    styleUrls: [],
    animations: [
        trigger('depositRequests', [
            transition('hide => show', useAnimation(fadeIn, {
                params: { timing: '1', delay: 0 }
            })),
            transition('show => hide', useAnimation(bounceOut, {
                params: { timing: '1', delay: 0 }
            })),
            state('hide', style({
                display: 'none',
            })),
            state('show', style({
                display: 'block',
            }))
        ]),
        trigger('newDepositRequest', [
            transition('hide => show', useAnimation(flipInY, {
                params: { timing: '1', delay: 0 }
            })),
            transition('show => hide', useAnimation(bounceOut, {
                params: { timing: '1', delay: 0 }
            })),
            state('hide', style({
                display: 'none',
            })),
            state('show', style({
                display: 'block',
            }))
        ]),
    ],
})

export class DepositComponent {

    lang: LanguageBase;
    constants: Constants;
    depositableCurrencies: any[];
    depositableCurrenciesSource: any[];
    depositRequestHistory: mdDepositRequestHistory[];
    depositableCurrenciesSettings: SearchableDropdownSettings
    depositRequestsSource: LocalDataSource = new LocalDataSource();
    feeSlabsDataSource: LocalDataSource = new LocalDataSource();
    selectedCurrency: any;
    loadingDepositableCurrencies: boolean = true;
    loadingDepositMethods: boolean = false;
    wallet: any;
    depositMethods: mdDepositMethods[];
    selectedDepositMethod: mdDepositMethods;
    depositMethodFeeSlabs: mdFeeSlabs[];
    feeSlabs: mdFeeSlabs[] = [];
    fee: string = '';
    form: FormGroup;
    model: mdDepositRequests;
    errors: any;
    showPreviousDepositRequests: boolean = false;
    showNewDespositRequestForm: boolean = false;
    submitted: boolean = false;
    submitResponseMessage: string = '';
    diableSubmitButton: boolean = false;
    showsubmitResponse: boolean = false;
    submitRequestResposneClass: string = '';
    depositRequestsTableSettings: any;
    feeSlabsSettings: any;
    defaultCurrencyId: number;
    depositableCurrenciesSelectedValue: any;
    afuConfig: any = {
        multiple: false,
        formatsAllowed: '.jpg,.jpeg,.png',
        maxSize: 2,
        uploadAPI: {
            url: '',
        },
        theme: 'dragNDrop',
    }
    resetAFU: boolean = true;
    fileUploaderConfig: mdFileUploaderConfig;
    resetFileUploader: boolean = false;
    fileUploaderValue: mdDigitalEvidence[] = [];
    fileUploaderBusy: boolean = false;

    constructor(
        private router: Router,
        private globals: GlobalsService,
        private log: LoggerService,
        private http: HttpClientService,
        private formBuilder: FormBuilder,
        private toaster: ToasterService
    ) {
    }

    ngOnInit() {
        this.lang = this.globals.lang;
        this.constants = Constants.Instance;
        this.depositableCurrenciesSettings = new SearchableDropdownSettings(
            300, true, true, 32, 32, this.lang.SelectCurrencyTodeposit,
        );
        this.loadDepositableCurrencies();

        this.model = new mdDepositRequests(true);
        this.form = this.formBuilder.group({
            amount: [
                this.model.amount,
                Validators.compose([
                    Validators.required,
                ])
            ],
            deposit_date: [
                this.model.deposit_date,
                Validators.compose([
                    Validators.required,
                ])
            ],
        });
        this.errors = {
            amountRequired: StaticHelper.formatString(this.lang.RequiredFormat, this.lang.Amount),
            depostiDateRequired: StaticHelper.formatString(this.lang.RequiredFormat, this.lang.DepositDate),
        };

        this.depositRequestsTableSettings = {
            hideSubHeader: true,
            actions: {
                add: false,
                edit: false,
                delete: false,
            },
            attr: {
                class: 'table-responsive funding-table',
            },
            rowClassFunction: () => {
                return 'color-white align-center';
            },
            columns: {
                id: {
                    title: this.lang.Id,
                    type: 'string',
                },
                currency: {
                    title: this.lang.Currency,
                    type: 'string',
                },
                amount: {
                    title: this.lang.Amount,
                    type: 'number',
                },
                deposit_date: {
                    title: this.lang.Date,
                    type: 'string',
                    valuePrepareFunction: (value: Date, row) => {
                        let dp = new DatePipe('en-US');
                        return dp.transform(value, 'medium');
                    }
                },
                record_status: {
                    title: this.lang.Status,
                    type: 'custom',
                    renderComponent: ButtonCellSmartTableRendererComponent,
                    onComponentInitFunction: (instance) => {
                        instance.save.subscribe((row: mdDepositRequestHistory) => {
                        });
                    },
                    valuePrepareFunction: (value: any, row: mdDepositRequestHistory) => {
                        let renderValue: mdButtonCellSmartTableRenderValue = new mdButtonCellSmartTableRenderValue();
                        renderValue.originalValue = value;
                        renderValue.text = StaticHelper.capitalizeFirstLetter(value);
                        renderValue.spinner = false;
                        renderValue.disabled = false;

                        if (renderValue.originalValue == EnumsDepositRequest.RecordStatus.pending) {
                            renderValue.class = 'warning';
                        }
                        else
                            if (renderValue.originalValue == EnumsDepositRequest.RecordStatus.rejected) {
                                renderValue.class = 'danger';
                            }
                            else
                                if (renderValue.originalValue == EnumsDepositRequest.RecordStatus.success) {
                                    renderValue.class = 'success';
                                }
                        renderValue.show = true;
                        return renderValue;
                    },
                    addable: false,
                    editable: false,
                    filter: false,
                },
            },
        };

        this.feeSlabsSettings = {
            hideSubHeader: true,
            actions: {
                add: false,
                edit: false,
                delete: false,
            },
            attr: {
                class: 'table-responsive funding-table',
            },
            rowClassFunction: () => {
                return 'color-white align-center';
            },
            columns: {
                from_volume: {
                    title: this.lang.Deposit + " " + this.lang.Amount,
                    type: 'string',
                    valuePrepareFunction: (value: number, row: mdFeeSlabs) => {
                        let tovol = " - " + row.to_volume.toString();
                        if(row.to_volume <= 0)
                        {
                            tovol = '';
                        }
                        if(tovol == '')
                        {
                            return " > " + row.from_volume;
                        }
                        return row.from_volume + tovol;
                    }
                },
                fee: {
                    title: this.lang.Fee,
                    type: 'string',
                    valuePrepareFunction: (value: number, row: mdFeeSlabs) => {
                        return this.getFeeStringFromFeeSlab(row);
                    }
                },
            },
        };

        this.fileUploaderConfig = new mdFileUploaderConfig(false, ['.jpg', '.jpeg', '.png'], 1, false, false, 
            this.lang.SelectFile, this.constants.EndPoints.PostDepositReceipt);
    }

    get f() { return this.form.controls; }

    depositDateChanged() {
        this.log.debug(this.f.deposit_date.value);
    }

    fileUploaderValueChanged(value)
    {
        this.fileUploaderValue = value;
    }

    newDepositRequestClicked() {
        this.form.reset();
        this.submitted = false;
        this.submitResponseMessage = '';
        this.diableSubmitButton = false;
        this.showNewDespositRequestForm = true;
        this.resetFileUploader = true;
    }

    loadDepositableCurrencies() {
        this.http.getPromise<mdCallResponse>(this.constants.EndPoints.GetDepositableCurrencies).then((data: mdCallResponse) => {

            if (data.isSuccess) {
                if (data.extras) {
                    if (data.extras.depositableCurrencies) {
                        this.depositableCurrencies = data.extras.depositableCurrencies;
                        this.defaultCurrencyId = data.extras.defaultCurrencyId;
                        this.depositableCurrenciesSource = this.depositableCurrencies.map(m => {
                            return {
                                text: m.name + ' (' + m.description + ')',
                                value: m.id,
                                image: m.icon,
                            }
                        });
                        let defaultCurrency = this.depositableCurrenciesSource.filter(m => m.value == this.defaultCurrencyId);
                        if (defaultCurrency.length > 0) {
                            this.depositableCurrenciesSelectedValue = defaultCurrency[0];
                            this.depositableCurrenciesOnChange({
                                newValue: this.depositableCurrenciesSelectedValue,
                                previousValue: null
                            });
                        }
                    }
                }
            }
            this.loadingDepositableCurrencies = false;

        }).catch(error => {
            this.log.error(error);
            this.loadingDepositableCurrencies = false;
        })
    }

    getFeeStringFromFeeSlab(fs: mdFeeSlabs)
    {
        let fee = '';
        if (fs.fee_type == EnumsFeeSlabs.FeeType.amount) {
            fee = this.selectedCurrency.symbol + fs.fee;
        }
        else
            if (fs.fee_type == EnumsFeeSlabs.FeeType.percentage) {
                fee = fs.fee_percentage + '%';
            }
            else
                if (fs.fee_type == EnumsFeeSlabs.FeeType.both) {
                    fee = StaticHelper.formatString(this.lang.WhichEverHigherFormat,
                        this.selectedCurrency.symbol + fs.fee,
                        fs.fee_percentage + '%',);
                }
                else {
                    fee = this.lang.Free
                }
        return fee;
    }

    setSelectedDepositMethod(newMethod: mdDepositMethods)
    {
        this.selectedDepositMethod = newMethod;
        this.depositMethodFeeSlabs = this.feeSlabs.filter(m => m.pk == this.selectedDepositMethod.id.toString());
        if (this.depositMethodFeeSlabs.length == 1) {
            this.fee = this.getFeeStringFromFeeSlab(this.depositMethodFeeSlabs[0]);
        }
        else if(this.depositMethodFeeSlabs.length > 1)
        {
            this.feeSlabsDataSource.load(this.depositMethodFeeSlabs);
        }
        else
        {
            this.fee = this.lang.Free
        }
    }

    depositableCurrenciesOnChange(event) {
        this.selectedCurrency = this.depositableCurrencies.filter(m => m.id == event.newValue.value)[0];
        this.loadDepositRequestHistory();
        this.showPreviousDepositRequests = false;
        this.loadingDepositMethods = true;
        this.http.postPromise<mdCallResponse>(this.constants.EndPoints.PostDepositMethods,
            { currency_id: event.newValue.value }).then((data: mdCallResponse) => {
                this.wallet = null;
                this.depositMethods = [];
                this.feeSlabs = [];
                this.setSelectedDepositMethod(null);
                if (data.isSuccess) {
                    this.wallet = data.extras.wallet;
                    this.feeSlabs = data.extras.feeSlabs as mdFeeSlabs[];
                    if(!this.feeSlabs)
                    {
                        this.feeSlabs = [];
                    }
                    this.depositMethods = data.extras.depositMethods as mdDepositMethods[];
                    if(!this.depositMethods)
                    {
                        this.depositMethods = [];
                    }
                    if (this.depositMethods.length > 0) {
                        this.setSelectedDepositMethod(this.depositMethods[0]);
                    }

                    if (!this.showPreviousDepositRequests) {
                        this.showPreviousDepositRequests = true;
                    }
                }
                this.loadingDepositMethods = false;
            }).catch(error => {
                this.loadingDepositMethods = false;
                this.log.error(error);
            })
    }

    loadDepositRequestHistory() {
        let model: mdDepositRequestHisotryRequest = new mdDepositRequestHisotryRequest();
        model.currency_id = this.selectedCurrency.id;
        model.rpp = 6;
        model.last = 0;
        this.depositRequestHistory = [];
        this.loadDepositRequestsTable();
        this.http.postPromise(this.constants.EndPoints.PostDepositRequestHistory, model).then((res: mdCallResponse) => {
            if (res.isSuccess) {
                this.depositRequestHistory = res.extras as mdDepositRequestHistory[];
            }
            else {
                this.depositRequestHistory = [];
            }
            this.log.debug(this.depositRequestHistory);
            this.loadDepositRequestsTable();
        }).catch(error => {
            this.depositRequestHistory = [];
            this.loadDepositRequestsTable();
            this.log.error(error);
        });
    }

    loadDepositRequestsTable() {
        this.depositRequestsSource.load(this.depositRequestHistory);
    }

    depositFormCancelButtonClicked() {
        this.showNewDespositRequestForm = false;
        this.resetFileUploader = false;
    }

    submitDepositRequest() {
        this.submitted = true;
        if (this.form.invalid) {
            return;
        }

        if (!this.selectedCurrency) {
            this.showsubmitResponse = true;
            this.submitRequestResposneClass = 'text-danger';
            this.submitResponseMessage = this.lang.NoCurrencySelected;
            return;
        }

        this.submitResponseMessage = "";
        this.diableSubmitButton = true;
        let formData: mdDepositRequests = this.form.value;
        formData.currency_id = this.selectedCurrency.id;
        formData.deposit_method_id = this.selectedDepositMethod.id;
        formData.reference = this.wallet.reference;
        formData.de = this.fileUploaderValue.map(m => {
            return m.id;
        });

        this.diableSubmitButton = true;
        this.http.postPromise<mdCallResponse>(this.constants.EndPoints.PostDepositRequest, formData).then((res: mdCallResponse) => {
            this.log.debug(res);
            if (res) {
                if (res.isSuccess) {
                    //show model
                    this.toaster.Success(StaticHelper.formatString(this.lang.CreatedSuccessfullyFormat, this.lang.DepositRequest));
                    this.submitRequestResposneClass = "text-success";
                    this.showNewDespositRequestForm = false;
                    this.resetFileUploader = false;
                    if (res.extras) {
                        if (res.extras.id) {
                            this.depositRequestHistory.unshift(res.extras);
                            this.loadDepositRequestsTable();
                        }
                    }
                }
                else {
                    this.submitRequestResposneClass = "text-danger";
                    this.hideSpinnerAndShowError(StaticHelper.bulletList(res.message.split("\n")));
                }
            }
        }).catch((error) => {
            this.log.debug(error);
            this.submitRequestResposneClass = "text-danger";
            this.log.debug(this.submitRequestResposneClass);
            this.showsubmitResponse = true;
            this.diableSubmitButton = false;
            this.submitResponseMessage = this.lang.UnableToCompleteYourRequest;
        });

    }

    hideSpinnerAndShowError(message = null) {
        if (!message) {
            message = this.lang.AccountCreatedLoginToContinue;
        }
        this.submitResponseMessage = message;
        this.showsubmitResponse = true;
        this.diableSubmitButton = false;
    }

}

<div class="row" style="margin:0;">
    <div class="col-md-6" style="padding-top:12px; padding-bottom:12px;">
        <searchable-dropdown width="100%" [showSpinner]="loadingDepositableCurrencies" [source]="depositableCurrenciesSource"
            [settings]="depositableCurrenciesSettings" [selectedValue]="depositableCurrenciesSelectedValue" (change)="depositableCurrenciesOnChange($event)">
        </searchable-dropdown>
        <div style="min-height:300px;" class="col-sm-12">
            <table *ngIf="wallet != null" class="table-responsive funding-wallet">
                <colgroup style="width:120px;"></colgroup>
                <colgroup style="width:160px;"></colgroup>
                <tr>
                    <th [innerHTML]="lang.TotalBalance"></th>
                    <td [innerHTML]="wallet.balance + ' ' + selectedCurrency.name"></td>
                </tr>
                <tr>
                    <th [innerHTML]="lang.OnHold"></th>
                    <td [innerHTML]="wallet.hold_balance + ' ' + selectedCurrency.name"></td>
                </tr>
                <tr>
                    <th [innerHTML]="lang.AvailableBalance"></th>
                    <td [innerHTML]="wallet.available_balance + ' ' + selectedCurrency.name"></td>
                </tr>
            </table>
            <hr *ngIf="selectedDepositMethod != null">
            <table *ngIf="selectedDepositMethod != null" class="table-responsive funding-deposit-methods">
                <colgroup style="width:180px;"></colgroup>
                <colgroup style="width:auto;"></colgroup>
                <tr>
                    <th [innerHTML]="lang.AccountName"></th>
                    <td [innerHTML]="selectedDepositMethod.account_name"></td>
                </tr>
                <tr>
                    <th [innerHTML]="lang.Address"></th>
                    <td [innerHTML]="selectedDepositMethod.address"></td>
                </tr>
                <tr>
                    <th [innerHTML]="lang.IBAN"></th>
                    <td [innerHTML]="selectedDepositMethod.iban"></td>
                </tr>
                <tr>
                    <th [innerHTML]="lang.BankName"></th>
                    <td [innerHTML]="selectedDepositMethod.bank_name"></td>
                </tr>
                <tr>
                    <th [innerHTML]="lang.Branch"></th>
                    <td [innerHTML]="selectedDepositMethod.branch_address"></td>
                </tr>
                <tr>
                    <th [innerHTML]="lang.Reference"></th>
                    <td [innerHTML]="wallet.reference"></td>
                </tr>
                <tr>
                    <th [innerHTML]="lang.Minimum"></th>
                    <td [innerHTML]="selectedCurrency.symbol + selectedDepositMethod.minimum_deposit"></td>
                </tr>
                <tr *ngIf="fee != null && fee != '' && depositMethodFeeSlabs.length <= 1">
                    <th [innerHTML]="lang.Fee"></th>
                    <td [innerHTML]="fee"></td>
                </tr>
                <tr *ngIf="depositMethodFeeSlabs.length > 1">
                    <th [innerHTML]="lang.Fee"></th>
                    <td>
                        <ng2-smart-table [settings]="feeSlabsSettings" [source]="feeSlabsDataSource">
                        </ng2-smart-table>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div [@depositRequests]="showPreviousDepositRequests ? 'show' : 'hide'" class="col-md-6" style="padding-top:12px; padding-bottom:12px;">
        <div [@newDepositRequest]="showNewDespositRequestForm ? 'show' : 'hide'">
            <h4 class="form-heading" [innerHTML]="lang.New + ' ' + lang.DepositRequest"></h4>
            <div class="tab-pane fade in active stylish-border">
                <form [formGroup]="form" style="margin:20px;" class="form-horizontal">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="col-sm-3 input-label" [innerHTML]="lang.Amount + (selectedCurrency ? ' (' + selectedCurrency.name + ')' : '')"></label>
                                <div class="col-md-9">
                                    <input [min]="selectedDepositMethod ? selectedDepositMethod.minimum_deposit : 0" number-only class="form-control" type="number" placeholder="{{lang.Amount}}"
                                        formControlName="amount" [ngClass]="{ 'is-invalid': submitted && f.amount.errors }" />
                                    <div *ngIf="submitted && f.amount.errors" class="invalid-feedback">
                                        <div *ngIf="f.amount.errors.required" [innerHtml]="errors.amountRequired"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="col-sm-3 input-label" [innerHTML]="lang.DepositDate"></label>
                                <div class="col-md-9">
                                    <input formControlName="deposit_date" readonly class="form-control" [placeholder]="lang.DepositDate"
                                        [ngClass]="{ 'is-invalid': submitted && f.deposit_date.errors }"
                                        [owlDateTimeTrigger]="dt1" [owlDateTime]="dt1" (dateTimeChange)="depositDateChanged()">
                                    <owl-date-time [pickerType]="'calendar'" #dt1></owl-date-time>
                                    <div *ngIf="submitted && f.deposit_date.errors" class="invalid-feedback">
                                        <div *ngIf="f.deposit_date.errors.required" [innerHtml]="errors.depostiDateRequired"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="col-sm-3 input-label" [innerHTML]="lang.Reference"></label>
                                <div class="col-md-9">
                                        <label class="col-sm-3 input-label" [innerHTML]="wallet ? wallet.reference : ''"></label>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12 color-white">
                            <div class="form-group">
                                <label class="col-sm-3 input-label" [innerHTML]="lang.DepositDate"></label>
                                <div class="col-md-9">
                                    <file-uploader 
                                        [config]="fileUploaderConfig"
                                        [reset]="resetFileUploader"
                                        (valueChange)="fileUploaderValueChanged($event)"
                                        [(isBusy)]="fileUploaderBusy">
                                    </file-uploader>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6" align="center">
                            <button style="width:100%" (click)="submitDepositRequest()" [nbSpinner]="diableSubmitButton || fileUploaderBusy" class="btn btn-success" [disabled]="diableSubmitButton" [innerHTML]="lang.Submit"></button>
                        </div>
                        <div class="col-sm-6" align="center">
                            <button style="width:100%" class="btn btn-default" (click)="depositFormCancelButtonClicked();" [innerHTML]="lang.Cancel"></button>
                        </div>
                        <div class="col-sm-12">
                                <div class="{{submitRequestResposneClass}} submit-response" *ngIf="showsubmitResponse"
                                    [innerHtml]="submitResponseMessage"></div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <table width="100%">
            <colgroup style="width:50%;"></colgroup>
            <colgroup style="width:50%;"></colgroup>
            <tbody>
                <tr>
                    <td class="funding-table-heading" [innerHTML]="lang.DepositRequest + '(s)'"></td>
                    <td align="right">
                        <button class="btn btn-xs btn-primary" (click)="newDepositRequestClicked()">
                            <i class="fa fa-plus"></i>&nbsp;<span [innerHTML]="lang.DepositRequest"></span>
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
        <ng2-smart-table [settings]="depositRequestsTableSettings" [source]="depositRequestsSource">
        </ng2-smart-table>
    </div>
</div>

// client/src/app/modules/funding/DepositComponent.tsx

import * as React from "react";
import { SearchableDropdownSettings } from "../shared/searchable-dropdown/searchable-dropdown-settings";
import FileUploaderComponent from "../shared/file-uploader/FileUploaderComponent";
import { mdFileUploaderConfig } from "../shared/file-uploader/file-uploader-config";
import { BaseComponent } from "../../components/base/BaseComponent";
import { mdDepositRequests } from "../../../models/deposit-requests";
import { mdFeeSlabs } from "../../../models/fee-slabs";
import { mdDepositMethods } from "../../../models/deposit-methods";
import { mdFormControl } from "../../../shared/form-control";
import { Transitions } from "../../../models/transitions";
import { TransitionState } from "../../../enums/transition";
import { StaticHelper } from "../../../shared/static-helper";
import { mdDepositRequestHistory } from "../../../models/deposit-request-history";
import { mdCallResponse } from "../../../models/call-response";
import { mdDepositRequestHisotryRequest } from "../../../models/deposit-request-history-request";
import * as ValidationAttributes from "../../../shared/validation-attributes";
import * as EnumsFeeSlabs from "../../../enums/fee-slabs";
import { Row, Card, Select, Table, Form, Col, Button, Tag } from "antd";
import "./deposit-component.css";
import { DepositRequestRecordStatuses } from "../../../enums/deposit-requests";
const Option = Select.Option;

export default class DepositComponent extends BaseComponent {

  render() {
    this.initShorts();
    let settings = this.state.depositableCurrenciesSettings;
    let cp = this.state.selectedCurrency;
    let wallet = this.state.wallet;
    let sdm = this.state.selectedDepositMethod;
    return (
      <>
        <Row>
          {
            this.colmd12(
              <Card className="gx-card" title={this.lang.Deposit}>
                <Select
                  showSearch
                  className="gx-w-100 mb-3 gx-vertical-align-middle"
                  optionFilterProp="children"
                  onChange={this.depositableCurrenciesOnChange}
                  filterOption={(input, option) => option.props.children.toString().toLowerCase().indexOf(input.toLowerCase()) >= 0}
                  value={cp ? cp.id : null}
                  size={'large'}
                >
                  {
                    this.state.depositableCurrenciesSource.map((s, i) => {
                      return <Option key={i} value={s.value}>
                        <img width={settings.imageWidth}
                          height={settings.imageHeight}
                          src={s.image} />
                        &nbsp;
                        {s.text}
                      </Option>
                    })
                  }
                </Select>
                {
                  <table className="funding-wallet">
                    <colgroup style={{ width: '120px' }}></colgroup>
                    <colgroup style={{ width: '160px' }}></colgroup>
                    <tbody>
                      <tr>
                        <th>{this.lang.TotalBalance}</th>
                        <td>{wallet ? this.state.wallet.balance.toFixed(cp.scale) + ' ' + cp.name : ''}</td>
                      </tr>
                      <tr>
                        <th>{this.lang.OnHold}</th>
                        <td>{wallet ? this.state.wallet.hold_balance.toFixed(cp.scale) + ' ' + cp.name : ''}</td>
                      </tr>
                      <tr>
                        <th>{this.lang.AvailableBalance}</th>
                        <td>{wallet ? this.state.wallet.available_balance.toFixed(cp.scale) + ' ' + cp.name : ''}</td>
                      </tr>
                    </tbody>
                  </table>
                }{
                  <>
                    <hr />
                    <table className="table-responsive ">
                      <colgroup style={{ width: '180px' }}></colgroup>
                      <colgroup style={{ width: 'auto' }}></colgroup>
                      <tbody>
                        <tr>
                          <th>{this.lang.AccountName}</th>
                          <td>{sdm ? sdm.account_name : ''}</td>
                        </tr >
                        <tr>
                          <th>{this.lang.Address}</th>
                          <td>{sdm ? sdm.address : ''}</td>
                        </tr >
                        <tr>
                          <th>{this.lang.IBAN}</th>
                          <td>{sdm ? sdm.iban : ''}</td>
                        </tr >
                        <tr>
                          <th>{this.lang.BankName}</th>
                          <td>{sdm ? sdm.bank_name : ''}</td>
                        </tr >
                        <tr>
                          <th>{this.lang.Branch}</th>
                          <td>{sdm ? sdm.branch_address : ''}</td>
                        </tr >
                        <tr>
                          <th>{this.lang.Reference}</th>
                          <td>{wallet ? wallet.reference : ''}</td>
                        </tr >
                        <tr>
                          <th>{this.lang.Minimum}</th>
                          <td>{sdm ? this.state.selectedCurrency.symbol + sdm.minimum_deposit : ''}</td>
                        </tr >
                        {
                          (!this.isNullOrEmpty(this.state.fee) && this.state.depositMethodFeeSlabs.length <= 1) ? (
                            <tr>
                              <th>{this.lang.Fee}</th>
                              <td>{this.state.fee}</td>
                            </tr >
                          ) : null
                        }
                        {
                          this.state.depositMethodFeeSlabs.length > 1 ? (
                            <tr>
                              <th>{this.lang.Fee}</th>
                              <td>
                                <Table className="gx-table-responsive"
                                  columns={this.feeSlabsTableSettings.columns}
                                  dataSource={this.state.depositMethodFeeSlabs}
                                  size="small"
                                  pagination={false}
                                />
                              </td >
                            </tr >
                          ) : null
                        }
                      </tbody>
                    </table>
                  </>

                }
              </Card>
            )
          }
          {
            this.colmd12(
              this.animatedCSSDivWithAttr(
                <>
                  {
                    this.animatedCSSDivWithAttr(
                      <Card className="gx-card" title={this.lang.New + " " + this.lang.Deposit}>

                        <Form onSubmit={this.submitDepositRequest} className="gx-signin-form gx-form-row0">
                          {
                            this.numberFormItem(this.f.amount, true, 25, sdm ? sdm.minimum_deposit : 0, 9999999, null, this.formItemLayout)
                          }
                          {
                            this.dateFormItem(this.f.deposit_date, true, this.formItemLayout)
                          }
                          <Row>
                            <Col xs={this.formItemLayout.labelCol.xs}
                              sm={this.formItemLayout.labelCol.sm}
                              md={this.formItemLayout.labelCol.md} style={{ paddingLeft: 0 }}>
                              <label style={{ margin: '0 8px 0 2px' }}>{this.lang.Reference}</label>
                            </Col>
                            <Col {...this.formItemLayout.wrapperCol}>
                              <p className="gx-mb-2 gx-text-primary gx-font-weight-semi-bold gx-fs-lg">
                                {wallet ? wallet.reference : ''}
                              </p>
                            </Col>
                          </Row>
                          <Row>
                            <Col xs={this.formItemLayout.labelCol.xs}
                              sm={this.formItemLayout.labelCol.sm}
                              md={this.formItemLayout.labelCol.md} style={{ paddingLeft: 0 }}>
                              <label style={{ margin: '0 8px 0 2px' }}>{this.lang.DepositReceipt}</label>
                            </Col>
                            <Col {...this.formItemLayout.wrapperCol}>
                              <FileUploaderComponent {...this.props}
                                ref={this.depositReceiptFileUploader}
                                params={{
                                  config: this.state.fileUploaderConfig,
                                  valueChange: this.fileUploaderValueChanged,
                                  isBusy: this.state.fileUploaderBusy,
                                  isBusyChange: this.fileUploaderisBusyChange
                                }}
                              />
                            </Col>
                          </Row>
                          <Row>
                            {
                              this.colmd12(
                                <Button loading={this.state.disableSubmitButton}
                                  type={"primary"}
                                  style={{ width: '100%' }}
                                  htmlType="submit">
                                  {this.lang.Submit}
                                </Button>)
                            }
                            {
                              this.colmd12(
                                <Button loading={false}
                                  type={"default"}
                                  style={{ width: '100%' }}
                                  htmlType="button"
                                  onClick={this.depositFormCancelButtonClicked}
                                >
                                  {this.lang.Cancel}
                                </Button>)
                            }
                          </Row>
                        </Form>

                      </Card>
                      , null, this.state.animValues.newDepositRequest
                    )
                  }
                  <Col span={8} offset={16}>
                    <Button loading={false}
                      type={"primary"}
                      htmlType="button"
                      onClick={this.newDepositRequestClicked}
                      style={{ alignContent: 'right' }}
                      size={"small"}
                    >
                      {
                        this.faicon("plus")
                      }
                      <i className="fa fa-plus"></i>&nbsp;<span>{this.lang.NewDepositRequest}</span>
                    </Button>
                  </Col>
                  <Card className="gx-card"
                    title={this.lang.DepositRequests}
                    extra={<p className="gx-text-primary gx-mb-0 gx-pointer">{this.lang.DetailedHistory}</p>}>
                    <Table className="gx-table-responsive"
                      columns={this.depositRequestsTableSettings.columns}
                      dataSource={this.state.depositRequestHistory}
                      size="small"
                      pagination={false}
                    />
                  </Card>

                </>, null, this.state.animValues.depositRequests)
            )
          }
        </Row>
      </>
    );
  }

  formItemLayout = {
    colon: false,
    labelAlign: 'left',
    labelCol: {
      xs: { span: 24 },
      sm: { span: 8 },
      md: { span: 6 },
      style: {
        paddingLeft: 0,
        paddingRight: 0,
        textAlign: 'left',
      }
    },
    wrapperCol: {
      xs: { span: 24 },
      sm: { span: 16 },
      md: { span: 18 },
      style: {
        paddingLeft: 0,
        paddingRight: 0,
      }
    },
  };
  model: mdDepositRequests;
  feeSlabs: mdFeeSlabs[] = [];
  depositMethods: mdDepositMethods[];
  // depositRequestHistory: mdDepositRequestHistory[];
  // depositableCurrenciesDropdown = React.createRef<SearchableDropdownComponent>();
  depositReceiptFileUploader = React.createRef<FileUploaderComponent>();
  feeSlabsTableSettings: any;
  depositRequestsTableSettings: any;

  constructor(props) {
    super(props);
    this.init();
  }

  init() {
    this.model = new mdDepositRequests(true);
    this.state = {
      form: {
        amount: new mdFormControl('', "amount", this.lang.Amount, [
          new ValidationAttributes.RequiredValidator(this.lang.RequiredFormat),
        ]),
        deposit_date: new mdFormControl(this.model.deposit_date, "deposit_date", this.lang.DepositDate, [
          new ValidationAttributes.RequiredValidator(this.lang.RequiredFormat),
        ]),
      },
      fileUploaderConfig: new mdFileUploaderConfig(false, ['.jpg', '.jpeg', '.png'], 1, false, false,
        this.lang.SelectFile, this.constants.EndPoints.PostDepositReceipt),
      depositableCurrenciesSettings: new SearchableDropdownSettings(
        300, true, true, 32, 32, this.lang.SelectCurrencyTodeposit),
      fileUploaderValue: [],
      disableSubmitButton: false,
      showSubmitResponse: false,
      submitResponseClass: 'text-danger',
      submitResponse: '',
      showErrors: false,
      showNewDespositRequestForm: false,
      loadingDepositableCurrencies: true,
      depositableCurrencies: [],
      defaultCurrencyId: null,
      depositableCurrenciesSource: [],
      selectedCurrency: null,
      selectedDepositMethod: null,
      depositMethodFeeSlabs: new mdFeeSlabs(),
      fee: '',
      wallet: null,
      depositRequestHistory: [],
      animValues: {
        depositRequests: new mdFormControl(this.getTransisition(Transitions.bounseOutHide2s, TransitionState.Completed), 'depositRequests'),
        newDepositRequest: new mdFormControl(this.getTransisition(Transitions.bounseOutHide2s, TransitionState.Completed), 'newDepositRequest')
      }
    }
    this.loadDepositableCurrencies();
    this.feeSlabsTableSettings = {
      attr: {
        className: 'table-responsive funding-table',
      },
      rowClassFunction: () => {
        return 'color-white align-center';
      },
      columns: [
        {
          title: this.lang.Deposit + " " + this.lang.Amount,
          dataIndex: 'from_volume',
          render: (value: number, row: mdFeeSlabs) => {
            let tovol = " - " + row.to_volume.toString();
            if (row.to_volume <= 0) {
              tovol = '';
            }
            if (tovol == '') {
              return " > " + row.from_volume;
            }
            return row.from_volume + tovol;
          },
        },
        {
          title: this.lang.Fee,
          dataIndex: 'fee',
          render: (value: number, row: mdFeeSlabs) => {
            return this.getFeeStringFromFeeSlab(row);
          },
        }
      ]
    };
    this.depositRequestsTableSettings = {
      hideSubHeader: true,
      actions: {
        add: false,
        edit: false,
        delete: false,
      },
      attr: {
        className: 'table-responsive funding-table',
      },
      rowClassFunction: () => {
        return 'color-white align-center';
      },
      columns: [
        {
          title: this.lang.Id,
          dataIndex: 'id',
        },
        {
          title: this.lang.Amount,
          dataIndex: 'amount',
          render: (value: number, row) => {
            return value + " " + row.currency;
          }
        },
        {
          title: this.lang.Date,
          dataIndex: 'created_timestamp',
          render: (value: Date, row) => {
            return StaticHelper.longDateFormat(value);
          }
        },
        {
          title: this.lang.Status,
          dataIndex: 'record_status',
          render: (value: any, row: mdDepositRequestHistory) => {
            let displayValue = StaticHelper.capitalizeFirstLetter(value);
            if (value == DepositRequestRecordStatuses.pending) {
              return <Tag color="orange">{displayValue}</Tag>;
            }
            else
              if (value == DepositRequestRecordStatuses.rejected) {
                return <Tag color="red">{displayValue}</Tag>;
              }
              else
                if (value == DepositRequestRecordStatuses.success) {
                  return <Tag color="green">{displayValue}</Tag>;
                }
                else {
                  return <Tag color="geekblue">{displayValue}</Tag>;
                }
          },
          addable: false,
          editable: false,
          filter: false,
        },
      ]
    };

  }

  fileUploaderValueChanged = (value) => {
    this.updateState({
      fileUploaderValue: value,
    })
  }

  newDepositRequestClicked = () => {
    this.showErrors = false;
    this.depositReceiptFileUploader.current.recievedNewChanges();
    this.updateState({
      disableSubmitButton: false,
      showSubmitResponse: false,
      submitResponseClass: 'text-danger',
      submitResponse: '',
      showNewDespositRequestForm: true,
      form: {
        amount: new mdFormControl('', "amount", this.lang.Amount, [
          new ValidationAttributes.RequiredValidator(this.lang.RequiredFormat),
        ]),
        deposit_date: new mdFormControl(this.model.deposit_date, "deposit_date", this.lang.DepositDate, [
          new ValidationAttributes.RequiredValidator(this.lang.RequiredFormat),
        ]),
      },
    }, () => {
      this.updateAnimValue(this.state.animValues.newDepositRequest.name, Transitions.flipInY, TransitionState.Running);
    })
  }

  loadDepositableCurrencies() {
    this.http.get<mdCallResponse>(this.constants.EndPoints.GetDepositableCurrencies).then((res: mdCallResponse) => {
      if (res.isSuccess) {
        if (res.extras) {
          if (res.extras.depositableCurrencies) {
            let depositableCurrenciesSource = res.extras.depositableCurrencies.map(m => {
              return {
                text: m.name + ' (' + m.description + ')',
                value: m.id,
                image: m.icon,
              }
            });


            this.updateState({
              depositableCurrencies: res.extras.depositableCurrencies,
              defaultCurrencyId: res.extras.defaultCurrencyId,
              depositableCurrenciesSource: depositableCurrenciesSource,
              loadingDepositableCurrencies: false,
            }, () => {
              let selectedValue = null;
              let defaultCurrency = depositableCurrenciesSource.filter(m => m.value == res.extras.defaultCurrencyId);
              if (defaultCurrency.length > 0) {
                selectedValue = defaultCurrency[0];
                this.depositableCurrenciesOnChange(selectedValue.value);
              }
            });
            // this.depositableCurrenciesDropdown.current.selectionChanged(selectedValue);
            // if (defaultCurrency.length > 0) {
            //   this.depositableCurrenciesOnChange({
            //     newValue: selectedValue,
            //     previousValue: null
            //   });
            // }
          }
        }
      }

    }).catch(error => {
      this.log.error(error);
      this.updateState({
        loadingDepositableCurrencies: false
      });
    })
  }

  getFeeStringFromFeeSlab(fs: mdFeeSlabs) {
    let fee = '';
    if (fs.fee_type == EnumsFeeSlabs.FeeType.amount) {
      fee = this.state.selectedCurrency.symbol + fs.fee;
    }
    else
      if (fs.fee_type == EnumsFeeSlabs.FeeType.percentage) {
        fee = fs.fee_percentage + '%';
      }
      else
        if (fs.fee_type == EnumsFeeSlabs.FeeType.both) {
          fee = StaticHelper.formatString(this.lang.WhichEverHigherFormat,
            this.state.selectedCurrency.symbol + fs.fee,
            fs.fee_percentage + '%');
        }
        else {
          fee = this.lang.Free
        }
    return fee;
  }

  setSelectedDepositMethod(newMethod: mdDepositMethods) {
    let fee = '';
    if (!newMethod) {
      this.updateState({
        selectedDepositMethod: newMethod,
        depositMethodFeeSlabs: [],
        fee: fee,
      });
      return;
    }
    let depositMethodFeeSlabs = newMethod ? this.feeSlabs.filter(m => m.pk == newMethod.id.toString()) : [];
    if (depositMethodFeeSlabs.length == 1) {
      fee = this.getFeeStringFromFeeSlab(depositMethodFeeSlabs[0]);
    }
    else if (depositMethodFeeSlabs.length > 1) {
      // this.feeSlabsTable.current.load(depositMethodFeeSlabs);
      // this.feeSlabsDataSource.load(depositMethodFeeSlabs);
    }
    else {
      fee = this.lang.Free
    }
    depositMethodFeeSlabs = depositMethodFeeSlabs.map((m, i) => {
      m["key"] = i;
      return m;
    })
    this.updateState({
      selectedDepositMethod: newMethod,
      depositMethodFeeSlabs: depositMethodFeeSlabs,
      fee: fee,
    })
  }

  depositableCurrenciesOnChange = (value) => {
    if (!value) {
      return;
    }
    let selectedCurrency = this.state.depositableCurrencies.filter(m => m.id == value)[0];
    this.updateState({
      selectedCurrency: selectedCurrency,
      wallet: null,
      selectedDepositMethod: null,
    }, () => {
      this.setSelectedDepositMethod(null);
      this.updateAnimValue(this.state.animValues.depositRequests.name, Transitions.bounseOutHide2s, TransitionState.Completed);
      this.loadDepositRequestHistory();
      // this.showPreviousDepositRequests = false;
      // this.loadingDepositMethods = true;
      this.http.post<mdCallResponse>(this.constants.EndPoints.PostDepositMethods,
        { currency_id: value }).then((data: mdCallResponse) => {
          this.depositMethods = [];
          this.feeSlabs = [];
          if (data.isSuccess) {
            this.feeSlabs = data.extras.feeSlabs as mdFeeSlabs[];
            if (!this.feeSlabs) {
              this.feeSlabs = [];
            }
            this.depositMethods = data.extras.depositMethods as mdDepositMethods[];
            if (!this.depositMethods) {
              this.depositMethods = [];
            }

            this.updateState({
              wallet: data.extras.wallet,
            })

            if (this.depositMethods.length > 0) {
              this.setSelectedDepositMethod(this.depositMethods[0]);
            }

            this.updateAnimValue(this.state.animValues.depositRequests.name, Transitions.fadeIn2s, TransitionState.Running);
          }
          // this.loadingDepositMethods = false;
        }).catch(error => {
          // this.loadingDepositMethods = false;
          this.log.error(error);
        })
    })
  }

  loadDepositRequestHistory = () => {
    let model: mdDepositRequestHisotryRequest = new mdDepositRequestHisotryRequest();
    model.currency_id = this.state.selectedCurrency.id;
    model.rpp = 8;
    model.last = null;
    model.order = "desc";
    this.updateState({
      depositRequestHistory: []
    })
    this.loadDepositRequestsTable();
    this.http.post(this.constants.EndPoints.PostDepositRequestHistory, model).then((res: mdCallResponse) => {
      let depositRequestHistory = [];
      if (res.isSuccess) {
        depositRequestHistory = res.extras as mdDepositRequestHistory[];
      }
      else {
        depositRequestHistory = [];
      }
      depositRequestHistory = depositRequestHistory.map(m => {
        m["key"] = m.id;
        return m;
      });
      this.updateState({
        depositRequestHistory: depositRequestHistory
      })
      // this.loadDepositRequestsTable();
    }).catch(error => {
      this.updateState({
        depositRequestHistory: []
      })
      // this.loadDepositRequestsTable();
      this.log.error(error);
    });
  }

  loadDepositRequestsTable() {
    // this.depositRequestsSource.load(this.depositRequestHistory);
  }

  depositFormCancelButtonClicked = (e) => {
    e.preventDefault();
    this.updateAnimValue(this.state.animValues.newDepositRequest.name, Transitions.bounseOutHide2s, TransitionState.Running);
    this.updateState({
      showNewDespositRequestForm: false,
    })
  }

  submitDepositRequest = (e) => {
    e.preventDefault();
    this.showErrors = true;
    // stop here if form is invalid
    if (!this.validateForm('form')) {
      this.log.debug("invalid form");
      return;
    }

    if (!this.state.selectedCurrency) {
      this.updateState({
        showSubmitResponse: true,
        submitResponseClass: 'text-danger',
        submitResponse: this.lang.NoCurrencySelected,
      })
      return;
    }

    this.updateState({
      showSubmitResponse: true,
      submitResponseClass: 'text-danger',
      submitResponse: '',
      disableSubmitButton: true,
    })

    let formData: mdDepositRequests = this.getFormData(this.state.form) as mdDepositRequests;
    formData.currency_id = this.state.selectedCurrency.id;
    formData.deposit_method_id = this.state.selectedDepositMethod.id;
    formData.reference = this.state.wallet.reference;
    formData.de = this.state.fileUploaderValue.map(m => {
      return m.id;
    });

    this.http.post<mdCallResponse>(this.constants.EndPoints.PostDepositRequest, formData).then((res: mdCallResponse) => {
      this.log.debug(res);
      if (res) {
        if (res.isSuccess) {
          //show model
          // this.toaster.Success(StaticHelper.formatString(this.lang.CreatedSuccessfullyFormat, this.lang.DepositRequest));
          this.successNotification(StaticHelper.formatString(this.lang.CreatedSuccessfullyFormat,
            this.lang.DepositRequest), this.lang.Success)
          this.updateState({
            submitResponseClass: 'text-success',
            showNewDespositRequestForm: false,
          })
          this.updateAnimValue(this.state.animValues.newDepositRequest.name, Transitions.bounseOutHide2s, TransitionState.Running);
          if (res.extras) {
            if (res.extras.id) {
              let depositRequestHistory = this.state.depositRequestHistory;
              depositRequestHistory.unshift(res.extras);
              this.updateState({
                depositRequestHistory: depositRequestHistory
              })
              // this.loadDepositRequestsTable();
            }
          }
        }
        else {
          this.errorNotification(res.message, this.lang.Error);
          this.hideSpinnerAndShowError(this.bulletList(res.message.split("\n")));
        }
      }
    }).catch((error) => {
      this.log.debug(error);
      this.errorNotification(this.lang.ErrorOccured, this.lang.Error);
      this.hideSpinnerAndShowError(this.lang.UnableToCompleteYourRequest);
    });

  }

  fileUploaderisBusyChange = (value) => {
    this.updateState({
      fileUploaderBusy: value
    })
  }

  hideSpinnerAndShowError(message = null) {
    if (!message) {
      message = this.lang.AccountCreatedLoginToContinue;
    }
    this.updateState({
      submitResponseClass: 'text-danger',
      showSubmitResponse: true,
      disableSubmitButton: false,
      submitResponse: message,
    })
  }

}
