// client/src/app/components/account/AccountVerificationComponent.tsx
import { BaseComponent } from "../base/BaseComponent";
import * as React from "react";
import { Link } from "react-router-dom";
import { StaticHelper } from "../../../shared/static-helper";
import { mdFormControl } from "../../../shared/form-control";
import { mdCallResponse } from "../../../models/call-response";

export default class AccountVerificationComponent extends BaseComponent {

    render() {
        this.initShorts();
        return (
            <div className="mainpage clearfix">
                <section className="signupwrap clearfix">
                    <div className="container">
                        <div className="row">
                            <div className="col-md-6 col-md-offset-3 col-sm-12">
                                <p className="h3">Account Verification</p>
                                <p className="p pstylish">{this.state.verificationResponse}</p>
                            </div>
                        </div>
                    </div>
                </section>
            </div >
        );
    }

    constructor(props) {
        super(props);
        this.init();
    }

    init() {
        this.state = {
            verificationResponse: this.lang.Verifying
        }
        let key: string = this.parsedLocation[this.constants.QueryParams.key];
        if (key) {
            this.verifyAccount(key);
        }
    }

    verifyAccount(key: string) {
        this.showMainSpinner();
        this.http.post<mdCallResponse>(this.constants.EndPoints.PostAccountVerify, { key: key }).then((res: mdCallResponse) => {
            if (res) {
                this.setState({
                    verificationResponse: res.message
                })
                if (!res.isSuccess) {
                    this.displayMessage(res.message);
                }
                else {
                    setTimeout(() => {
                        window.location.replace(this.constants.RoutePaths.Login);
                    }, 2 * 1000);
                }
                this.hideMainSpinner();
            }
        }).catch(error => {
            this.log.debug(error);
            this.hideMainSpinner();
        });
    }

}

// client/src/app/components/account-verification/account-verification.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute, ParamMap } from '@angular/router'
import { LanguageBase } from '../../shared/language';
import { SpinnerService } from 'src/app/services/spinner.service';
import { mdCallResponse } from 'src/app/models/call-response';
import { HttpClientService } from 'src/app/services/http-client.service';
import { LoggerService } from 'src/app/services/logger.service';
import { ConfirmationBoxService } from 'src/app/services/confirmation-box.service';
import { GlobalsService } from 'src/app/services/globals.service';
import { Constants } from '../../shared/constants';

@Component({
    selector: 'app-account-verification',
    templateUrl: './account-verification.component.html'
})
export class AccountVerificationComponent implements OnInit {

    lang: LanguageBase;
    verificationResponse: string;
    constants: Constants;
    constructor(private router: Router, 
        private route: ActivatedRoute, 
        private spinner: SpinnerService,
        private http: HttpClientService, 
        private log: LoggerService, 
        private alertBox: ConfirmationBoxService,
        private globals: GlobalsService) {
        spinner.show();
    }

    ngOnInit() {
        this.constants = this.globals.constants;
        this.lang = this.globals.lang;
        this.verificationResponse = this.lang.Verifying;
        let key: string = "";
        this.route.queryParams
            .subscribe((params: ParamMap) => {
                key = params[this.constants.QueryParams.key];
            });
        if (!key) {
            this.spinner.hide();
            //show verify account ui
        }
        else {
            this.verifyAccount(key);
        }
    }

    verifyAccount(key: string) {
        this.spinner.show();
        let res: mdCallResponse = new mdCallResponse();
        this.http.post<mdCallResponse>(this.constants.EndPoints.PostAccountVerify, { key: key }).subscribe((data) => {
            res = data;
        }, error => {
            this.spinner.hide();
        }, () => {
            if (res) {
                this.spinner.hide();
                this.verificationResponse = res.message;
                if (!res.isSuccess) {
                    this.alertBox.displayMessage(res.message);
                }
                else {
                    setTimeout(() => {
                        window.location.replace(this.constants.RoutePaths.Login);
                    }, 2 * 1000);
                }
            }
        });
    }

}
