// client/src/app/components/order/order.component.ts
import { Component, OnInit, Input, EventEmitter, SimpleChanges } from '@angular/core';
import { LoggerService } from 'src/app/services/logger.service';
import { LanguageBase } from 'src/app/shared/language';
import { GlobalsService } from 'src/app/services/globals.service';
import { FormGroup, FormBuilder } from '@angular/forms';
import { mdOrder } from 'src/app/models/order';
import { mdCallResponse } from 'src/app/models/call-response';
import { HttpClientService } from 'src/app/services/http-client.service';
import { SpinnerService } from 'src/app/services/spinner.service';
import { StaticHelper } from 'src/app/shared/static-helper';
import { Constants } from 'src/app/shared/constants';

@Component({
    selector: 'app-trade-order',
    templateUrl: './order.component.html',
    styleUrls: []
})

export class OrderComponent implements OnInit {

    @Input() currencyPair: any;
    lang: LanguageBase;
    buyBalance: string;
    sellBalance: string;
    availableBalance: number;
    bform: FormGroup;
    sform: FormGroup;
    model: mdOrder;
    sellTotalAmount: string;
    alertClass: string;
    alertMessage: string;
    displayAlert: boolean;
    limitBuyTotalAmount: string;
    limitBuyGrossAmount: string;
    limitBuyFeeAmount: string;
    limitSellTotalAmount: string;
    limitSellGrossAmount: string;
    limitSellFeeAmount: string;
    priceStep: number;
    amountStep: number;
    submitted: boolean;
    constants: Constants;
    constructor(private log: LoggerService, 
        public globals: GlobalsService, 
        private formBuilder: FormBuilder,
        private http: HttpClientService, 
        private spinner: SpinnerService) {

    }

    ngOnInit() {
        this.constants = this.globals.constants;
        this.displayAlert = false;
        this.alertClass = "";
        this.alertMessage = "";
        this.lang = this.globals.lang;
        this.availableBalance;
        this.model = new mdOrder(true);
        this.bform = this.formBuilder.group({
            price: [
                this.model.price,
                null
            ],
            amount: [
                this.model.amount,
            ],
        });
        this.sform = this.formBuilder.group({
            price: [
                this.model.price,
                null
            ],
            amount: [
                this.model.amount,
            ],
        });
    }

    get bf() { return this.bform.controls; }

    get sf() { return this.sform.controls; }

    ngOnChanges(changes: SimpleChanges) {
        this.currencyPair = changes.currencyPair.currentValue;
        this.spinner.show();
        this.loadBalanceAndFee();
    }

    loadBalanceAndFee() {
        this.sellBalance = "";
        this.buyBalance = "";
        
        if (this.currencyPair.id) {
            let res: mdCallResponse = new mdCallResponse();
            this.http.post<mdCallResponse>(this.constants.EndPoints.PostPairDetails, this.currencyPair.id).subscribe((data) => {
                res = data;
            }, (error) => {
                this.log.debug(error);
                this.spinner.hide();
            }, () => {
                if (res.isSuccess) {
                    Object.assign(this.currencyPair, res.extras);
                    this.log.debug(this.currencyPair);
                    this.updateBalances();
                }
                this.spinner.hide();
            });
        }
    }

    updateBalances() {
        this.sellBalance = (this.currencyPair.fc_available_balance / this.constants.Float)
            .toFixed(this.currencyPair.fc_scale) + " " + this.currencyPair.fc_name;
        this.buyBalance = (this.currencyPair.tc_available_balance / this.constants.Float)
            .toFixed(this.currencyPair.tc_scale) + " " + this.currencyPair.tc_name;
        this.limitBuyFeeAmount = StaticHelper.bestScale(StaticHelper.unfloatAmount(this.currencyPair.buy_fee)) + "%";
        this.limitSellFeeAmount = StaticHelper.bestScale(StaticHelper.unfloatAmount(this.currencyPair.sell_fee)) + "%";
        this.priceStep = 1 / Math.pow(10, StaticHelper.minScale(this.currencyPair.tc_scale));
        this.amountStep = 1 / Math.pow(10, StaticHelper.minScale(this.currencyPair.fc_scale));
    }

    onSubmit(action: number) {
        //validate form locally
        let formData: mdOrder;
        if (action == this.constants.Order.Action.buy) {
            formData = this.bform.value;
        }
        else
            if (action == this.constants.Order.Action.sell) {
                formData = this.sform.value;
            }
        formData.action = action;
        formData.currencyPair = this.currencyPair.id;
        formData.type = this.constants.Order.Type.limit;
        let res: mdCallResponse = new mdCallResponse();
        this.spinner.show();
        this.http.post<mdCallResponse>(this.constants.EndPoints.PostOrder, formData).subscribe((data) => {
            res = data;
        },
            (error) => {
                this.log.debug(error);
                this.spinner.hide();
            },
            () => {
                this.log.debug(res);
                this.displayAlertBox(res.isSuccess, res.message);
                this.loadBalanceAndFee();
                if (action == this.constants.Order.Action.buy) {
                    this.bf.amount.setValue(0);
                    this.priceAmountKeyup(this.bf);
                }
                else
                    if (action == this.constants.Order.Action.sell) {
                        this.sf.amount.setValue(0);
                        this.priceAmountKeyup(this.sf);
                    }
                this.spinner.hide();
            });
    }

    displayAlertBox(isSuccess: boolean, message: string) {
        if (isSuccess) {
            this.alertClass = "alert alert-success";
        }
        else {
            this.alertClass = "alert alert-danger";
        }
        if (message) {
            message = StaticHelper.bulletList(message.split("\n"));
        }
        this.alertMessage = message;
        this.displayAlert = true;
        setTimeout(() => {
            this.displayAlert = false;
        }, this.constants.ResponseMessageTimeout * 1000);
    }

    priceAmountKeyup(f) {
        let grossAmount = f.price.value * f.amount.value;
        if (f == this.bf) {
            let feeAmount = grossAmount * (StaticHelper.unfloatAmount(this.currencyPair.buy_fee) / 100);
            let totalAmount = grossAmount + feeAmount;
            this.limitBuyGrossAmount = StaticHelper.bestScale(grossAmount)
                + " " + this.currencyPair.tc_name;
            //this.limitBuyFeeAmount = feeAmount.toFixed(StaticHelper.bestScale(0));
            this.limitBuyTotalAmount = totalAmount.toFixed(StaticHelper.minScale(this.currencyPair.tc_scale)) + " " + this.currencyPair.tc_name;;
        }
        else {
            let feeAmount = grossAmount * (StaticHelper.unfloatAmount(this.currencyPair.sell_fee) / 100);
            let totalAmount = grossAmount + feeAmount;
            this.limitSellGrossAmount = StaticHelper.bestScale(grossAmount)
                + " " + this.currencyPair.tc_name;
            //this.limitSellFeeAmount = feeAmount.toFixed(StaticHelper.bestScale(0));
            this.limitSellTotalAmount = totalAmount.toFixed(StaticHelper.minScale(this.currencyPair.tc_scale)) + " " + this.currencyPair.tc_name;;
        }
    }

}

<div class="row">
    <div class=" col-md-12">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#star-tab">{{lang.Limit}}</a></li>
            <li><a data-toggle="tab" href="#usd-tab">{{lang.Market}}</a></li>
            <!-- <li><a data-toggle="tab" href="#eur-tab">Stop-Loss</a></li> -->
        </ul>
        <div class="tab-content">
            <div id="star-tab" class="tab-pane fade in active">
                <div class="row">
                    <div class="col-md-6">
                        <div class="tabs_das">
                            <h3>{{lang.AvailableBalance}}<span [innerHTML]="buyBalance"></span></h3>
                            <form [formGroup]="bform" (ngSubmit)="onSubmit(constants.Order.Action.buy)">
                                <div class="input_elment">
                                    <label [innerHTML]="lang.Price"></label>
                                    <input (input)="priceAmountKeyup(bf)" type="number" min="0" class="form-control"
                                        [step]="priceStep" number-only placeholder="{{currencyPair.tc_name}}"
                                        formControlName="price" [ngClass]="{ 'is-invalid': submitted && bf.price.errors }" />
                                </div>
                                <div class="input_elment">
                                    <label [innerHTML]="lang.Amount"></label>
                                    <input (input)=priceAmountKeyup(bf) type="number" [step]="amountStep" min="0" class="form-control"
                                        number-only placeholder="{{currencyPair.fc_name}}" formControlName="amount"
                                        [ngClass]="{ 'is-invalid': submitted && bf.amount.errors }" />
                                </div>
                                <div class="vin">
                                    <span>25%</span>&nbsp;<span>50%</span>&nbsp;<span>75%</span>&nbsp;<span>100%</span>
                                </div>
                                <div class="to_amount">
                                    <label [innerHTML]="lang.Gross"></label>
                                    <span [innerHTML]="limitBuyGrossAmount"></span>
                                </div>
                                <div class="to_amount">
                                    <label [innerHTML]="lang.Fee"></label>
                                    <span [innerHTML]="limitBuyFeeAmount"></span>
                                </div>
                                <div class="to_amount">
                                    <label [innerHTML]="lang.Total"></label>
                                    <span [innerHTML]="limitBuyTotalAmount"></span>
                                </div>
                                <button class="buy_bt">
                                    <img src="assets/images/buy-icon.png" style="width:20px; margin-right:10px;"
                                        alt="lang.Buy">
                                    <span [innerHTML]="lang.Buy"></span>
                                </button>
                            </form>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="tabs_das">
                            <h3>{{lang.AvailableBalance}}<span [innerHTML]="sellBalance"></span></h3>
                            <form [formGroup]="sform" (ngSubmit)="onSubmit(constants.Order.Action.sell)">
                                <div class="input_elment">
                                    <label [innerHTML]="lang.Price"></label>
                                    <input (input)=priceAmountKeyup(sf) type="number" min="0" [step]="priceStep" class="form-control"
                                        number-only placeholder="{{currencyPair.tc_name}}" formControlName="price"
                                        [ngClass]="{ 'is-invalid': submitted && sf.price.errors }" />
                                </div>
                                <div class="input_elment">
                                    <label [innerHTML]="lang.Amount"></label>
                                    <input (input)=priceAmountKeyup(sf) type="number" [step]="amountStep" min="0" class="form-control"
                                        number-only placeholder="{{currencyPair.fc_name}}" formControlName="amount"
                                        [ngClass]="{ 'is-invalid': submitted && sf.amount.errors }" />
                                </div>
                                <div class="vin">
                                    <span>25%</span>&nbsp;<span>50%</span>&nbsp;<span>75%</span>&nbsp;<span>100%</span>
                                </div>
                                <div class="to_amount">
                                    <label [innerHTML]="lang.Gross"></label>
                                    <span [innerHTML]="limitSellGrossAmount"></span>
                                </div>
                                <div class="to_amount">
                                    <label [innerHTML]="lang.Fee"></label>
                                    <span [innerHTML]="limitSellFeeAmount"></span>
                                </div>
                                <div class="to_amount">
                                    <label [innerHTML]="lang.Total"></label>
                                    <span [innerHTML]="limitSellTotalAmount"></span>
                                </div>
                                <button class="buy_bt bt_dark"><img src="assets/images/sell-icon.png" style="width:20px; margin-right:5px;"
                                        alt="lang.Sell"> <span [innerHTML]="lang.Sell"></span></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div id="usd-tab" class="tab-pane fade ">
                <div class="row">
                    <div class="col-md-6">
                        <div class="tabs_das">
                            <h3>Buy APPC <span>0.000002019 BTC</span></h3>
                            <form>
                                <div class="input_elment">
                                    <label>Price </label>
                                    <select name="">
                                    </select>
                                </div>
                                <div class="input_elment">
                                    <label>Amount </label>
                                    <input name="" type="text" value="APPC">
                                </div>
                                <div class="vin"> <span>25%</span> <span>50%</span> <span>75%</span> <span>100%</span></div>
                                <div class="to_amount">
                                    <label>Total</label>
                                    <span>0.0000000BTC</span> </div>
                                <button type="button" class="buy_bt bt_dark"><img src="assets/images/sell-icon.png"
                                        style="width:20px; margin-right:5px;" alt="img"> Buy</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div id="eur-tab" class="tab-pane fade in">
                <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table-responsive">
                    <tr>
                        <td align="center" valign="middle" class="white-txt"><i class="fa fa-star" aria-hidden="true"></i>
                            BTCUSD</td>
                        <td align="center" valign="middle" class="white-txt">7,486.2</td>
                        <td align="center" valign="middle" class="white-txt">-1.5%</td>
                        <td align="center" valign="middle" class="white-txt">7,599.7</td>
                        <td align="center" valign="middle" class="white-txt">7,413.8</td>
                        <td align="center" valign="middle" class="white-txt">135,942,900 USD</td>
                    </tr>
                    <tr>
                        <td align="center" valign="middle" class="white-txt"><i class="fa fa-star" aria-hidden="true"></i>
                            BTCUSD</td>
                        <td align="center" valign="middle" class="white-txt">988.82</td>
                        <td align="center" valign="middle" class="white-txt">-3.6%</td>
                        <td align="center" valign="middle" class="white-txt">1,030.0</td>
                        <td align="center" valign="middle" class="white-txt">982.24 </td>
                        <td align="center" valign="middle" class="white-txt">24,967,202 USD</td>
                    </tr>
                    <tr>
                        <td align="center" valign="middle" class="white-txt"><i class="fa fa-star" aria-hidden="true"></i>
                            BTCUSD</td>
                        <td align="center" valign="middle" class="white-txt">7,486.2</td>
                        <td align="center" valign="middle" class="white-txt">-1.5%</td>
                        <td align="center" valign="middle" class="white-txt">7,599.7</td>
                        <td align="center" valign="middle" class="white-txt">7,413.8</td>
                        <td align="center" valign="middle" class="white-txt">135,942,900 USD</td>
                    </tr>
                    <tr>
                        <td align="center" valign="middle" class="white-txt"><i class="fa fa-star" aria-hidden="true"></i>
                            BTCUSD</td>
                        <td align="center" valign="middle" class="white-txt">988.82</td>
                        <td align="center" valign="middle" class="white-txt">-3.6%</td>
                        <td align="center" valign="middle" class="white-txt">1,030.0</td>
                        <td align="center" valign="middle" class="white-txt">982.24 </td>
                        <td align="center" valign="middle" class="white-txt">24,967,202 USD</td>
                    </tr>
                </table>
            </div>
            <div *ngIf="displayAlert" [class]="alertClass" [innerHTML]="alertMessage"></div>
        </div>
    </div>
</div>

// client/src/modules/trade/OrderComponent.tsx
import { BaseComponent } from "../../app/components/base/BaseComponent";
import * as React from "react";
import { mdOrder } from "../../models/order";
import { mdFormControl } from "../../shared/form-control";
import * as ValidationAttributes from "../../shared/validation-attributes";
import { mdCallResponse } from "../../models/call-response";
import { StaticHelper } from "../../shared/static-helper";
import * as EnumsOrder from "../../enums/order";
import NBSpinnerComponent from "../shared/spinner/NBSpinnerComponent";

export default class OrderComponent extends BaseComponent {

    render() {
        this.initShorts();
        this.componentMountedFirstTime = true;
        return (
            <div className="row">
                <div className=" col-md-12">
                    <NBSpinnerComponent {...this.props} params={{ show: this.state.showSpinner }} />
                    <ul className="nav nav-tabs">
                        <li className="active"><a data-toggle="tab" href="#star-tab">{this.lang.Limit}</a></li>
                        {/* <li><a data-toggle="tab" href="#usd-tab">{{lang.Market}}</a></li>
            <li><a data-toggle="tab" href="#eur-tab">Stop-Loss</a></li> */}
                    </ul>
                    <div className="tab-content">
                        <div id="star-tab" className="tab-pane fade in active">
                            <div className="row">
                                <div className="col-md-6">
                                    <div className="tabs_das">
                                        <h3>{this.lang.AvailableBalance}<span>{this.state.buyBalance}</span></h3>
                                        <form>
                                            <div className="input_elment">
                                                <label>{this.lang.Price}</label>
                                                {
                                                    this.numberInput(this, this.state.bform.price, (name, e) => {
                                                        this.handleFormControlInput(name, e, "bform");
                                                        this.priceAmountKeyup(EnumsOrder.Action.buy);
                                                    }, this.state.priceStep, 0, 9999999, this.currencyPair ? this.currencyPair.tc_name : "")
                                                }
                                            </div>
                                            <div className="input_elment">
                                                <label>{this.lang.Amount}</label>
                                                {
                                                    this.numberInput(this, this.state.bform.amount, (name, e) => {
                                                        this.handleFormControlInput(name, e, "bform");
                                                        this.priceAmountKeyup(EnumsOrder.Action.buy);
                                                    }, this.state.amountStep, 0, 9999999, this.currencyPair ? this.currencyPair.fc_name : "")
                                                }
                                            </div>
                                            <div className="vin">
                                                <span>25%</span>&nbsp;<span>50%</span>&nbsp;<span>75%</span>&nbsp;<span>100%</span>
                                            </div>
                                            <div className="to_amount">
                                                <label>{this.lang.Gross}</label>
                                                <span>{this.state.limitBuyGrossAmount}</span>
                                            </div>
                                            <div className="to_amount">
                                                <label>{this.lang.Fee}</label>
                                                <span>{this.state.limitBuyFeeAmount}</span>
                                            </div>
                                            <div className="to_amount">
                                                <label>{this.lang.Total}</label>
                                                <span>{this.state.limitBuyTotalAmount}</span>
                                            </div>
                                            <button className={`buy_bt ${this.state.disableBuyButton ? 'nb-spinner-container' : ''}`}
                                                disabled={this.state.disableBuyButton}
                                                onClick={(e) => { this.onSubmit(EnumsOrder.Action.buy, e) }}>
                                                <NBSpinnerComponent {...this.props} params={{ show: this.state.disableBuyButton }} />
                                                <img src="assets/images/buy-icon.png" style={{ width: '20px', marginRight: '10px' }}
                                                    alt="lang.Buy" />
                                                <span>{this.lang.Buy}</span>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                                <div className="col-md-6">
                                    <div className="tabs_das">
                                        <h3>{this.lang.AvailableBalance}<span>{this.state.sellBalance}</span></h3>
                                        <form>
                                            <div className="input_elment">
                                                <label>{this.lang.Price}</label>
                                                {
                                                    this.numberInput(this, this.state.sform.price, (name, e) => {
                                                        this.handleFormControlInput(name, e, "sform");
                                                        this.priceAmountKeyup(EnumsOrder.Action.sell);
                                                    }, this.state.priceStep, 0, 9999999, this.currencyPair ? this.currencyPair.tc_name : "")
                                                }
                                            </div>
                                            <div className="input_elment">
                                                <label>{this.lang.Amount}</label>
                                                {
                                                    this.numberInput(this, this.state.sform.amount, (name, e) => {
                                                        this.handleFormControlInput(name, e, "sform");
                                                        this.priceAmountKeyup(EnumsOrder.Action.sell);
                                                    }, this.state.amountStep, 0, 9999999, this.currencyPair ? this.currencyPair.fc_name : "")
                                                }
                                            </div>
                                            <div className="vin">
                                                <span>25%</span>&nbsp;<span>50%</span>&nbsp;<span>75%</span>&nbsp;<span>100%</span>
                                            </div>
                                            <div className="to_amount">
                                                <label>{this.lang.Gross}</label>
                                                <span>{this.state.limitSellGrossAmount}</span>
                                            </div>
                                            <div className="to_amount">
                                                <label>{this.lang.Fee}</label>
                                                <span>{this.state.limitSellFeeAmount}</span>
                                            </div>
                                            <div className="to_amount">
                                                <label>{this.lang.Total}</label>
                                                <span>{this.state.limitSellTotalAmount}</span>
                                            </div>
                                            <button className={`buy_bt bt_dark ${this.state.disableSellButton ? 'nb-spinner-container' : ''}`}
                                                disabled={this.state.disableSellButton}
                                                onClick={(e) => { this.onSubmit(EnumsOrder.Action.sell, e) }}>
                                                <NBSpinnerComponent {...this.props} params={{ show: this.state.disableSellButton }} />
                                                <img src="assets/images/sell-icon.png" style={{ width: '20px', marginRight: '5px' }}
                                                    alt="lang.Sell" />
                                                <span>{this.lang.Sell}</span>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {
                            this.getAlertDiv()
                        }
                    </div>
                </div>
            </div>
        );
    }

    currencyPair: any;
    model: mdOrder;

    constructor(props) {
        super(props);
        this.init();
    }

    init() {
        this.model = new mdOrder(true);
        this.state = {
            bform: {
                price: new mdFormControl('', "price", this.lang.Price, [
                    // new ValidationAttributes.RequiredValidator(this.lang.RequiredFormat),
                ]),
                amount: new mdFormControl('', "amount", this.lang.Amount, [
                    // new ValidationAttributes.RequiredValidator(this.lang.RequiredFormat),
                ]),
                showErrors: false,
            },
            sform: {
                price: new mdFormControl('', "price", this.lang.Price, [
                    // new ValidationAttributes.RequiredValidator(this.lang.RequiredFormat),
                ]),
                amount: new mdFormControl('', "amount", this.lang.Amount, [
                    // new ValidationAttributes.RequiredValidator(this.lang.RequiredFormat),
                ]),
                showErrors: false,
            },
            sellBalance: "",
            buyBalance: "",
            showSpinner: true,
            limitBuyGrossAmount: "",
            limitBuyTotalAmount: "",
            limitSellGrossAmount: "",
            limitSellTotalAmount: "",
            limitBuyFeeAmount: "",
            limitSellFeeAmount: "",
            priceStep: 1,
            amountStep: 1,
            disableBuyButton: false,
            disableSellButton: false,
        }
    }

    resetForm(action: EnumsOrder.Action) {
        if (action == EnumsOrder.Action.buy) {
            this.updateState({
                bform: {
                    price: new mdFormControl('', "price", this.lang.Price, [
                        // new ValidationAttributes.RequiredValidator(this.lang.RequiredFormat),
                    ]),
                    amount: new mdFormControl('', "amount", this.lang.Amount, [
                        // new ValidationAttributes.RequiredValidator(this.lang.RequiredFormat),
                    ]),
                    showErrors: false,
                },
                buyBalance: "",
                limitBuyGrossAmount: "",
                limitBuyTotalAmount: "",
                limitBuyFeeAmount: "",
                priceStep: 1,
                amountStep: 1,
            })
        }
        else {
            this.updateState({
                sform: {
                    price: new mdFormControl('', "price", this.lang.Price, [
                        // new ValidationAttributes.RequiredValidator(this.lang.RequiredFormat),
                    ]),
                    amount: new mdFormControl('', "amount", this.lang.Amount, [
                        // new ValidationAttributes.RequiredValidator(this.lang.RequiredFormat),
                    ]),
                    showErrors: false,
                },
                sellBalance: "",
                limitSellGrossAmount: "",
                limitSellTotalAmount: "",
                limitSellFeeAmount: "",
                priceStep: 1,
                amountStep: 1,
            })
        }
    }

    componentWillUpdate() {
        if (!this.currencyPair) {
            this.recievedNewChanges(this.g.selectedCurrencyPair);
        }
    }

    recievedNewChanges(newCP) {
        if (!newCP) {
            return;
        }
        let oldCP = this.currencyPair;
        if (oldCP) {
            if (oldCP.id == newCP.id) {
                return;
            }
        }
        this.currencyPair = newCP;
        if (this.currencyPair) {
            this.state = {
                ...this.state,
                showSpinner: true,
            }
            this.loadBalanceAndFee();
        }
    }

    loadBalanceAndFee() {
        this.updateState({
            sellBalance: "",
            buyBalance: "",
            showSpinner: true,
        })

        if (this.currencyPair.id) {
            this.http.post<mdCallResponse>(this.constants.EndPoints.PostPairDetails, this.currencyPair.id).then((res:mdCallResponse) => {
                if (res.isSuccess) {
                    Object.assign(this.currencyPair, res.extras);
                    this.log.debug(this.currencyPair);
                    this.updateBalances();
                }
                this.updateState({
                    showSpinner: false
                })
            }).catch((error) => {
                this.log.debug(error);
                this.updateState({
                    showSpinner: false
                })
            });
        }
    }

    updateBalances() {
        if (!this.currencyPair) {
            return;
        }
        this.updateState({
            sellBalance: (this.currencyPair.fc_available_balance / this.constants.Float)
                .toFixed(this.currencyPair.fc_scale) + " " + this.currencyPair.fc_name,
            buyBalance: (this.currencyPair.tc_available_balance / this.constants.Float)
                .toFixed(this.currencyPair.tc_scale) + " " + this.currencyPair.tc_name,
            limitBuyFeeAmount: StaticHelper.bestScale(StaticHelper.unfloatAmount(this.currencyPair.buy_fee)) + "%",
            limitSellFeeAmount: StaticHelper.bestScale(StaticHelper.unfloatAmount(this.currencyPair.sell_fee)) + "%",
            priceStep: 1 / Math.pow(10, StaticHelper.minScale(this.currencyPair.tc_scale)),
            amountStep: 1 / Math.pow(10, StaticHelper.minScale(this.currencyPair.fc_scale)),
        })
    }

    onSubmit(action: EnumsOrder.Action, e) {
        e.preventDefault();
        //validate form locally
        let formData: mdOrder;
        if (action == this.constants.Order.Action.buy) {
            if (!this.state.sform.showErrors) {
                this.updateState({
                    bform: {
                        ...this.state.bform,
                        showErrors: true,
                    }
                })
            }
            if (!this.validateForm("bform")) {
                return;
            }

            formData = this.getFormData(this.state.bform) as mdOrder;
            this.updateState({
                disableBuyButton: true,
            })
        }
        else
            if (action == this.constants.Order.Action.sell) {
                if (!this.state.sform.showErrors) {
                    this.updateState({
                        sform: {
                            ...this.state.sform,
                            showErrors: true,
                        }
                    })
                }
                if (!this.validateForm("sform")) {
                    return;
                }

                formData = this.getFormData(this.state.sform) as mdOrder;
                this.updateState({
                    disableSellButton: true,
                })
            }
        formData.action = action;
        formData.currencyPair = this.currencyPair.id;
        formData.type = this.constants.Order.Type.limit;
        let res: mdCallResponse = new mdCallResponse();

        this.http.post<mdCallResponse>(this.constants.EndPoints.PostOrder, formData).then((res: mdCallResponse) => {
            this.log.debug(res);
            this.showAlertDiv(res.isSuccess, res.message);
            this.loadBalanceAndFee();
            this.resetForm(action);

            this.updateState({
                disableSellButton: false,
                disableBuyButton: false,
            })
            if(res.isSuccess)
            {
                this.p.onNewOrder();
            }
        }).catch((error) => {
            this.log.debug(error);
            this.updateState({
                disableSellButton: false,
                disableBuyButton: false,
            })
        });
    }

    priceAmountKeyup(action: EnumsOrder.Action) {
        let f: any;
        f = action == EnumsOrder.Action.buy ? this.state.bform : this.state.sform;
        let grossAmount = f.price.value * f.amount.value;
        if (action == EnumsOrder.Action.buy) {
            let feeAmount = grossAmount * (StaticHelper.unfloatAmount(this.currencyPair.buy_fee) / 100);
            let totalAmount = grossAmount + feeAmount;
            this.updateState({
                limitBuyGrossAmount: StaticHelper.bestScale(grossAmount)
                    + " " + this.currencyPair.tc_name,
                limitBuyTotalAmount: totalAmount.toFixed(StaticHelper.minScale(this.currencyPair.tc_scale)) + " " + this.currencyPair.tc_name,
            })
        }
        else {
            let feeAmount = grossAmount * (StaticHelper.unfloatAmount(this.currencyPair.sell_fee) / 100);
            let totalAmount = grossAmount + feeAmount;
            this.updateState({
                limitSellGrossAmount: StaticHelper.bestScale(grossAmount)
                    + " " + this.currencyPair.tc_name,
                limitSellTotalAmount: totalAmount.toFixed(StaticHelper.minScale(this.currencyPair.tc_scale)) + " " + this.currencyPair.tc_name,
            })
        }
    }

}
