// client/src/app/components/account/LoginComponent.tsx
import { BaseComponent } from "../base/BaseComponent";
import * as React from "react";
import { Link } from "react-router-dom";
import { StaticHelper } from "../../../shared/static-helper";
import { mdFormControl } from "../../../shared/form-control";
import { mdCallResponse } from "../../../models/call-response";
import { mdSignUp, SignUpMetaData } from "../../../models/sign-up";
import * as ValidationAttributes from "../../../shared/validation-attributes"
import ReCAPTCHA from "react-google-recaptcha";
import { StaticConstatns } from "../../../shared/constants";

export default class LoginComponent extends BaseComponent {

    render() {
        this.initShorts();
        return (
            <div className="mainpage clearfix">
                <section className="signupwrap clearfix">
                    <div className="container">
                        <div className="row">
                            <div className="col-md-6 col-md-offset-3 col-sm-12">
                                <p className="h3">{this.lang.Login}</p>
                                <div className="signupbox clearfix">
                                    <ul className=" nav nav-tabs" style={{ border: 'none' }}>
                                        <li className="active">
                                            <a data-toggle="tab">
                                                <img src="assets/images/u-icon.png" alt={this.lang.Individual} />
                                                <span>{this.lang.Credentials}</span>
                                            </a>
                                        </li>
                                    </ul>
                                    <div className="tab-content">
                                        <div className="tab-pane fade in active">
                                            <form onSubmit={this.onSubmit}>
                                                <div className="row">
                                                    <div className="col-sm-12">
                                                        {
                                                            this.textFormControl(this.f.username, this.handleFormControlInput)
                                                        }
                                                    </div>
                                                    <div className="col-sm-12">
                                                        {
                                                            this.textFormControl(this.f.password, this.handleFormControlInput, true, "password")
                                                        }
                                                    </div>
                                                    {
                                                        global.isDev ? (null
                                                        ) : 
                                                        (
                                                            <div className="col-sm-12">
                                                            {
                                                                this.captchaFormControl(this.f.captcha, this.handleCaptchaInput) 
                                                            }
                                                            {/* //     <div className="form-group">
                                                            //         <ReCAPTCHA ref={this.captchaRef} className="no-form-control" sitekey={StaticConstatns.RecaptchaSiteKey} onChange={this.handleFormControlInput}/>
                                                            //         {
                                                            //             this.getErrosDiv(this.f.captcha)
                                                            //         }
                                                            //     </div> */}
                                                            </div>
                                                           )
                                                    }
                                                    <div className="col-sm-12">
                                                        <button className="signup-btn btn btn-primary">{this.lang.Login}</button>
                                                    </div>
                                                    <div className="col-sm-12">
                                                        <strong>
                                                            {
                                                                this.state.showSubmitResponse ? (
                                                                    <div className={`${this.state.submitResponseClass} text-bold`}>{this.state.submitResponse}</div>
                                                                ) : (null)
                                                            }

                                                        </strong>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div className="col-sm-12 pstylish color-white">
                                    <Link className="f-fl hyperlink-color" to={this.constants.RoutePaths.AccountForgotPassword}>
                                        {this.lang.ForgotPassword}
                                    </Link>
                                    <span className="f-fr">
                                        <span>{this.lang.NotJoinedBitvelocityYet}</span>
                                        <Link className="hyperlink-color" to={this.constants.RoutePaths.SignUp}>{this.lang.JoinNow}</Link>
                                    </span >
                                </div >
                            </div >
                        </div >
                    </div >
                </section >
            </div >
        );
    }

    redirectURI: string;
    model: mdSignUp;
    constructor(props) {
        super(props);
        this.init();
    }

    init() {
        this.redirectURI = this.parsedLocation[this.constants.QueryParams.redirectURI];
        if (!this.redirectURI) {
            this.redirectURI = this.constants.RoutePaths.Trade;
        }
        this.model = new mdSignUp(true);
        this.state = {
            form: {
                username: new mdFormControl(this.model.username, "username", this.lang.UserName, [
                    new ValidationAttributes.RequiredValidator(this.lang.RequiredFormat),
                    new ValidationAttributes.MaxLengthValidator(this.lang.MaxLengthFormat2,
                        SignUpMetaData.userNameMaxLength),
                ]),
                password: new mdFormControl(this.model.password, "password", this.lang.Password, [
                    new ValidationAttributes.RequiredValidator(this.lang.RequiredFormat),
                    new ValidationAttributes.MaxLengthValidator(this.lang.MaxLengthFormat2,
                        SignUpMetaData.passwordMaxLength),
                ]),
                captcha: global.isDev ? null : new mdFormControl(null, "captcha", '', [
                    new ValidationAttributes.RequiredValidator(this.lang.CapitchaErrorMessage)
                ])
            },
            diableSubmitButton: false,
            showSubmitResponse: false,
            submitResponseClass: 'text-danger',
            submitResponse: '',
        }
    }

    onSubmit = (e) => {
        e.preventDefault();
        this.showErrors = true;
        // let captchaToken = this.captchaRef.current.getValue();
        // this.log.info(captchaToken);
        // if (this.isNullOrEmpty(captchaToken) && !global.isDev) {
        //     return;
        // }

        if (!this.validateForm('form')) {
            this.log.debug("invalid form");
            return;
        }

        //everything is fine, now save the data
        this.updateState({
            submitResponse: '',
            diableSubmitButton: true
        })
        let formData: mdSignUp = this.getFormData(this.state.form) as mdSignUp;
        this.showMainSpinner();
        this.http.post<mdCallResponse>(this.constants.EndPoints.PostAuthLogin, formData).then((res: mdCallResponse) => {
            this.log.debug(res);
            if (res) {
                if (res.isSuccess) {
                    //signup completed, now sign in
                    if (res.extras) {
                        if (res.extras.status == this.constants.RecordStatus.PendingVerification) {
                            let emailConfirmationRout = "<a href='" + this.constants.RoutePaths.EmailConfirmation + "?" + this.constants.QueryParams.email + "=em'>" + this.lang.Here + "</a>"
                            res.message = StaticHelper.formatString(this.lang.EmailVerificationRequired, emailConfirmationRout);

                            this.hideSpinnerAndShowError(this.bulletList(res.message.split("\n")));
                        }
                        else {
                            if (this.redirectURI) {
                                window.location.href = this.redirectURI;
                            }
                            else {
                                window.location.href = this.constants.RoutePaths.Trade;
                            }
                        }
                    }
                }
                else {
                    this.hideSpinnerAndShowError(this.bulletList(res.message.split("\n")));
                }
            }
            this.hideMainSpinner();
        }).catch((error) => {
            this.log.debug(error);
            this.hideSpinnerAndShowError();
        });
    }

    hideSpinnerAndShowError(message = null) {
        if (!message) {
            message = this.lang.AccountCreatedLoginToContinue;
        }
        this.hideMainSpinner();
        this.updateState({
            diableSubmitButton: false,
            showSubmitResponse: true,
            submitResponse: message
        })
    }

}

// client/src/app/components/login/login.component.ts
import { Inject, Component, OnInit } from '@angular/core';

import { Http, Response, Headers, RequestOptions } from '@angular/http';
import { ActivatedRoute, ParamMap } from '@angular/router';
import { FormControl, FormGroup } from '@angular/forms';
import { Router } from '@angular/router';
import { NgxNotificationService } from 'ngx-notification';
import { FormBuilder, Validators } from '@angular/forms';
import { LocalStorage, SharedStorage } from 'ngx-store';
import { LanguageBase } from 'src/app/shared/language';
import { Constants } from 'src/app/shared/constants';
import { mdSignUp, SignUpMetaData } from 'src/app/models/sign-up';
import { HttpClientService } from 'src/app/services/http-client.service';
import { LoggerService } from 'src/app/services/logger.service';
import { SpinnerService } from 'src/app/services/spinner.service';
import { mdCallResponse } from 'src/app/models/call-response';
import { GlobalsService } from 'src/app/services/globals.service';
import { StaticHelper } from 'src/app/shared/static-helper';

declare var $: any;
@Component({
    selector: 'app-login',
    templateUrl: './login.component.html',
    styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
    lang: LanguageBase;
    const: Constants;
    model: mdSignUp;
    form: FormGroup;
    submitted = false;
    errors: any;
    submitResponseMessage: string;
    showsubmitResponse: boolean;
    submitRequestResposneClass: string;
    diableSubmitButton: boolean;
    redirectURI: string;


    constructor(private formBuilder: FormBuilder, private http: HttpClientService, private spinner: SpinnerService,
        private router: Router, private log: LoggerService, private route: ActivatedRoute, private globals: GlobalsService) {
    }

    ngOnInit() {
        this.lang = this.globals.lang;
        this.route.queryParams.subscribe((params: ParamMap) => {
            this.redirectURI = params[Constants.QueryParams.redirectURI];
        });
        if (!this.redirectURI) {
            this.redirectURI = Constants.RoutePaths.Trade;
        }
        this.const = Constants;
        this.showsubmitResponse = false;
        this.submitResponseMessage = "";
        this.submitRequestResposneClass = "";
        this.model = new mdSignUp(true);
        this.diableSubmitButton = false;
        this.form = this.formBuilder.group({
            username: [
                this.model.username,
                Validators.compose([
                    Validators.required,
                    Validators.maxLength(SignUpMetaData.userNameMaxLength)
                ])
            ],
            password: [
                this.model.password,
                Validators.compose([
                    Validators.required,
                    Validators.maxLength(SignUpMetaData.passwordMaxLength)
                ])
            ],
            captcha: !this.globals.isDev ? null : new FormControl(false, null)
        });
        this.errors = {
            usernameRequired: StaticHelper.formatString(this.lang.RequiredFormat, this.lang.UserName),
            passwordRequired: StaticHelper.formatString(this.lang.RequiredFormat, this.lang.Password),
            capitchaErrorMessage: this.lang.CapitchaErrorMessage,
        };
        this.spinner.hide();
    }

    onScriptLoad() {
        this.log.debug('Google reCAPTCHA loaded and is ready for use!')
    }

    onScriptError() {
        this.log.debug('Something went long when loading the Google reCAPTCHA')
    }
    // bool: any;
    // convenience getter for easy access to form fields
    get f() { return this.form.controls; }

    onSubmit() {
        this.submitted = true;
        if (this.form.controls.captcha.status != "VALID" && !this.globals.isDev) {
            return;
        }
        // stop here if form is invalid
        if (this.form.invalid) {
            return;
        }

        //everything is fine, now save the data
        this.submitResponseMessage = "";
        this.diableSubmitButton = true;
        let formData: mdSignUp = this.form.value;

        let res = new mdCallResponse();
        this.spinner.show();
        this.http.post<mdCallResponse>(Constants.EndPoints.PostAuthLogin, formData).subscribe((data) => {
            this.log.debug(data);
            res = data;
        },
            (error) => {
                this.log.debug(error);
                this.spinner.hide();
                this.showsubmitResponse = true;
                this.diableSubmitButton = false;
                this.submitResponseMessage = this.lang.UnableToCompleteYourRequest;
            },
            () => {
                this.spinner.hide();
                this.submitRequestResposneClass = "text-danger";
                this.log.debug(res);
                if (res) {
                    if (res.isSuccess) {
                        //signup completed, now sign in
                        if (res.extras) {
                            if (res.extras.status == Constants.RecordStatus.PendingVerification) {
                                let emailConfirmationRout = "<a href='" + Constants.RoutePaths.EmailConfirmation + "?" + Constants.QueryParams.email + "=em'>" + this.lang.Here + "</a>"
                                res.message = StaticHelper.formatString(this.lang.EmailVerificationRequired, emailConfirmationRout);

                                this.hideSpinnerAndShowError(StaticHelper.bulletList(res.message.split("\n")));
                            }
                            else {
                                window.location.href = this.redirectURI;
                            }
                        }
                    }
                    else {
                        this.hideSpinnerAndShowError(StaticHelper.bulletList(res.message.split("\n")));
                    }
                }
            });
    }

    hideSpinnerAndShowError(message = null) {
        this.spinner.hide();
        if (!message) {
            message = this.lang.AccountCreatedLoginToContinue;
        }
        this.submitResponseMessage = message;
        this.showsubmitResponse = true;
        this.diableSubmitButton = false;
    }
}

<div class="mainpage clearfix">
    <lib-ngx-notification></lib-ngx-notification>
    <!-- Signup Start -->
    <section class="signupwrap clearfix">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3 col-sm-12">
                    <h3 [innerHTML]="lang.Login"></h3>
                    <div class="signupbox clearfix">
                        <ul class=" nav nav-tabs" style="border:none;">
                            <li class="active">
                                <a data-toggle="tab">
                                    <img src="src/assets/images/u-icon.png" alt="Individual">
                                    <span [innerHTML]="lang.Credentials"></span>
                                </a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane fade in active">
                                <form [formGroup]="form" (ngSubmit)="onSubmit()">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <div class="form-group">
                                                <input class="form-control" placeholder="{{lang.UserName}}"
                                                    formControlName="username" [ngClass]="{ 'is-invalid': submitted && f.username.errors }" />
                                                <div *ngIf="submitted && f.username.errors" class="invalid-feedback">
                                                    <div *ngIf="f.username.errors.required" [innerHtml]="errors.usernameRequired"></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-12">
                                            <div class="form-group">
                                                <input type="password" class="form-control" placeholder="{{lang.Password}}"
                                                    formControlName="password" [ngClass]="{ 'is-invalid': submitted && f.password.errors }" />
                                                <div *ngIf="submitted && f.password.errors" class="invalid-feedback">
                                                    <div *ngIf="f.password.errors.required" [innerHtml]="errors.passwordRequired"></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-12" *ngIf="!globals.isDev">
                                            <div class="form-group">
                                                <re-captcha class="no-form-control" formControlName="captcha"
                                                    (scriptLoad)="onScriptLoad()" (scriptError)="onScriptError()"
                                                    [ngClass]="{ 'is-invalid': submitted && f.captcha.status != 'VALID' }">
                                                </re-captcha>
                                                <div *ngIf="submitted && f.captcha.status != 'VALID'" class="invalid-feedback">
                                                    <div [innerHtml]="errors.capitchaErrorMessage"></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-12">
                                            <button class="signup-btn btn btn-primary" [innerHTML]="lang.Login"></button>
                                        </div>
                                        <div class="col-sm-12">
                                          <strong>
                                            <div class="{{submitRequestResposneClass}} text-bold" *ngIf="showsubmitResponse" [innerHtml]="submitResponseMessage"></div>
                                          </strong>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12 pstylish color-white">
                        <a class="f-fl hyperlink-color" [routerLink]="'/' + const.RoutePaths.AccountForgotPassword"
                            [innerHTML]="lang.ForgotPassword"></a>
                        <span class="f-fr">
                            <span [innerHTML]="lang.NotJoinedBitvelocityYet"></span>
                            <a class="hyperlink-color" [routerLink]="'/' + const.RoutePaths.SignUp" [innerHTML]="lang.JoinNow"></a>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
