// client/src/app/components/signup/signup.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ValidationErrors, FormControl, AbstractControl } from '@angular/forms';
import { mdSignUp, SignUpMetaData } from '../../models/sign-up';
import { LanguageBase } from '../../shared/language';
import { HttpClientService } from '../../services/http-client.service';
import { SpinnerService } from '../../services/spinner.service';
import * as EmailValidator from 'email-validator';
import { v4 as uuid } from 'uuid';
import { Router } from '@angular/router'
import { mdCallResponse } from '../../models/call-response';
import { LoggerService } from '../../services/logger.service';
import { GlobalsService } from 'src/app/services/globals.service';
import { StaticHelper } from 'src/app/shared/static-helper';
import { Constants } from 'src/app/shared/constants';

@Component({
    selector: 'app-signup',
    templateUrl: './signup.component.html',
})
export class SignupComponent implements OnInit {
    // constants: Constants = new Constants();
    lang: LanguageBase;
    frmPersonal: mdSignUp;
    personalForm: FormGroup;
    submitted = false;
    errors: any;
    submitResponseMessage: string;
    showsubmitResponse: boolean;
    submitRequestResposneClass: string;
    invalidEmail: boolean;
    diableSubmitButton: boolean;
    passwordDidNotMatch: boolean;
    account_type: number;//1 for inidividual 2 for business
    constants: Constants;


    constructor(private formBuilder: FormBuilder, 
        private http: HttpClientService, 
        private spinner: SpinnerService, 
        private router: Router, 
        private log: LoggerService, 
        public globals:GlobalsService) {
    }

    ngOnInit() {
        this.constants = this.globals.constants;
        this.lang = this.globals.lang;
        this.account_type = 1;
        this.passwordDidNotMatch = true;
        this.showsubmitResponse = false;
        this.submitResponseMessage = "";
        this.submitRequestResposneClass = "";
        this.frmPersonal = new mdSignUp(true);
        this.invalidEmail = false;
        this.diableSubmitButton = false;
        this.personalForm = this.formBuilder.group({
            first_name: [
                this.frmPersonal.first_name,
                Validators.compose([
                    Validators.required,
                    Validators.maxLength(SignUpMetaData.firstNameMaxLength)
                ])
            ],
            last_name: [
                this.frmPersonal.last_name,
                Validators.compose([
                    Validators.required,
                    Validators.maxLength(SignUpMetaData.lastNameMaxLength)
                ])
            ],
            company_name: [
                this.frmPersonal.company_name, null
            ],
            email: [
                this.frmPersonal.email,
                Validators.compose([
                    Validators.required,
                    Validators.email,
                    Validators.maxLength(SignUpMetaData.emailMaxLength)
                ])
            ],
            // username: [
            //     this.frmPersonal.username,
            //     Validators.compose([
            //         Validators.required,
            //         // Validators.minLength(SignUpMetaData.userNameMinLength),
            //         Validators.pattern(new RegExp(SignUpMetaData.userNameRegex)),
            //         // Validators.pattern(new RegExp('^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#\$%\^&\*])(?=^.{8,32}$)(?=^\\S*$)')),
            //         // Validators.maxLength(SignUpMetaData.userNameMaxLength),
            //     ])
            // ],
            password: [
                this.frmPersonal.password,
                Validators.compose([
                    Validators.required,
                    Validators.pattern(new RegExp(SignUpMetaData.passwordRegex)),
                ])
            ],
            confirm_password: [
                this.frmPersonal.confirm_password,
            ],
            personal_capitcha: this.globals.isDev ? null : new FormControl(false, null)
        });
        this.errors = {
            first_nameRequired: StaticHelper.formatString(this.lang.RequiredFormat, this.lang.FirstName),
            first_nameMaxLength: StaticHelper.formatString(this.lang.MaxLengthFormat, SignUpMetaData.firstNameMaxLength),
            last_nameRequired: StaticHelper.formatString(this.lang.RequiredFormat, this.lang.LastName),
            last_nameMaxLength: StaticHelper.formatString(this.lang.MaxLengthFormat, SignUpMetaData.lastNameMaxLength),
            usernameRequired: StaticHelper.formatString(this.lang.RequiredFormat, this.lang.UserName),
            usernameRange: StaticHelper.formatString(this.lang.RangeLengthFormat, SignUpMetaData.userNameMinLength,
                SignUpMetaData.userNameMaxLength),
            usernamePattern: StaticHelper.bulletList(this.lang.UserNameRequirement, this.lang.UserName,
                SignUpMetaData.userNameMinLength, SignUpMetaData.userNameMaxLength),
            passwordRequired: StaticHelper.formatString(this.lang.RequiredFormat, this.lang.Password),
            passwordPattern: StaticHelper.bulletList(this.lang.PasswordRequirement, this.lang.Password, SignUpMetaData.passwordMinLength,
                SignUpMetaData.passwordMaxLength),
            emailRequired: StaticHelper.formatString(this.lang.RequiredFormat, this.lang.Email),
            emailInvalid: this.lang.InvalidEmail,
            passwordDidNotMatch: StaticHelper.formatString(this.lang.DidNotMatchFormat, this.lang.Password, this.lang.ConfirmPassword),
            capitchaErrorMessage: this.lang.CapitchaErrorMessage,
            company_nameRequired: StaticHelper.formatString(this.lang.RequiredFormat, this.lang.CompanyName),
            company_nameMaxLength: StaticHelper.formatString(this.lang.MaxLengthFormat, SignUpMetaData.companyNameMaxLength),
        };
    }

    signupType(type: number) {
        this.account_type = type;
        if (this.account_type == 1) {
            this.personalForm.controls.company_name.clearValidators();
        }
        else {
            this.personalForm.controls.company_name.setValidators(Validators.compose([
                Validators.required,
                Validators.maxLength(SignUpMetaData.companyNameMaxLength)
            ]));
        }

    }

    confirmPassowrdValidator(control: AbstractControl): { [key: string]: boolean } | null {

        if (this.personalForm.controls.password.value === this.personalForm.controls.confirm_password.value) {
            this.passwordDidNotMatch = false;
        }
        else {
            this.passwordDidNotMatch = true;
            if (this.personalForm.controls.confirm_password.errors) {
            }
            else {
                this.personalForm.controls.confirm_password.setErrors({ "nomatch": true });
            }
        }
        return null;

    }

    onScriptLoad() {
        this.log.debug('Google reCAPTCHA loaded and is ready for use!')
    }

    onScriptError() {
        this.log.debug('Something went long when loading the Google reCAPTCHA')
    }
    // bool: any;
    // convenience getter for easy access to form fields
    get pf() { return this.personalForm.controls; }

    matchPassword(ev: any) {
        if (this.submitted) {
            if (this.personalForm.controls.password.value === this.personalForm.controls.confirm_password.value) {
                this.passwordDidNotMatch = false;
            }
            else {
                this.passwordDidNotMatch = true;
                if (this.personalForm.controls.confirm_password.errors) {
                }
                else {
                    this.personalForm.controls.confirm_password.setErrors({ "nomatch": true });
                }
            }
        }
    }

    onEmailKeyUp(ev: any) {
        if (this.submitted) {
            if (!EmailValidator.validate(this.personalForm.controls.email.value)) {
                this.invalidEmail = true;
            }
            else {
                this.invalidEmail = false;
            }
        }
    }

    onSubmit() {
        this.submitted = true;
        if (this.personalForm.controls.personal_capitcha.status != "VALID" && !this.globals.isDev) {
            return;
        }
        // stop here if form is invalid
        if (this.personalForm.invalid) {
            return;
        }

        this.onEmailKeyUp(null);
        if (this.invalidEmail) {
            return;
        }

        this.matchPassword(null);
        if (this.passwordDidNotMatch) {
            return;
        }

        //everything is fine, now save the data
        this.diableSubmitButton = true;
        this.invalidEmail = false;
        let formData: mdSignUp = this.personalForm.value;
        formData.account_type = this.account_type;
        formData.uuid = uuid();

        let res = new mdCallResponse();
        this.spinner.show();
        this.http.post<mdCallResponse>(this.constants.EndPoints.PostAccountRegister, formData).subscribe((data) => {
            this.log.debug(data);
            res = data;
        },
            (error) => {
                this.log.debug(error);
                this.spinner.hide();
                this.showsubmitResponse = true;
                this.diableSubmitButton = false;
                this.submitResponseMessage = this.lang.UnableToCompleteYourRequest;
            },
            () => {
                // this.spinner.hide();
                this.submitRequestResposneClass = "text-danger";
                this.log.debug(res);
                if (res) {
                    if (res.isSuccess) {
                        //signup completed, now sign in
                        res = null;
                        var newFormData = {
                            username: formData.email,
                            password: formData.password,
                            grant_type: this.constants.GrantTypes.Password,
                        }
                        this.http.post<mdCallResponse>(this.constants.EndPoints.PostAuthLogin, newFormData).subscribe((data) => {
                            res = data;
                        },
                            (error) => {
                                this.log.debug(error);
                                this.hideSpinnerAndShowError();
                            },
                            () => {
                                this.submitRequestResposneClass = "text-danger";
                                this.log.debug(res);
                                if (res) {
                                    if (res.isSuccess) {
                                        //logged in successfully, now send email
                                        //navigate to /emailConfirmation we'll send email from there
                                        window.location.replace(this.constants.RoutePaths.EmailConfirmation + "?" + this.constants.QueryParams.email + "=em");//we just need to set something in this param if we want to send email on component load
                                    }
                                    else {
                                        this.hideSpinnerAndShowError();
                                        this.router.navigateByUrl(this.constants.RoutePaths.Login, { skipLocationChange: false });
                                    }
                                }
                                else {
                                    this.hideSpinnerAndShowError(StaticHelper.bulletList(res.message.split("\n")));
                                }
                            });
                    }
                    else {
                        this.hideSpinnerAndShowError(StaticHelper.bulletList(res.message.split("\n")));
                    }
                }
            });
    }

    hideSpinnerAndShowError(message = null) {
        this.spinner.hide();
        if (!message) {
            message = this.lang.AccountCreatedLoginToContinue;
        }
        this.submitResponseMessage = message;
        this.showsubmitResponse = true;
        this.diableSubmitButton = false;
    }
}


<div class="mainpage clearfix">
  <!-- Signup Start -->
  <section class="signupwrap clearfix">
    <div class="container">
      <!-- <h2>
        "As per the regulations all customers must have KYC verifications before buying selling can be enabled on
        their account"
      </h2> -->
      <div class="row">
        <div class="col-md-6 col-md-offset-3 col-sm-12">
          <h3>Create your account</h3>
          <div class="signupbox clearfix">
            <ul class="nav nav-tabs">
              <li class="active">
                <a data-toggle="tab" href="#Individual" (click)="signupType(1)">
                  <img src="assets/images/u-icon.png" alt="Individual"> Individual
                </a>
              </li>
              <li>
                <a data-toggle="tab" href="#Individual" (click)="signupType(2)">
                  <img src="assets/images/b-icon.png" alt="Business"> Business <i></i>
                </a>
              </li>
            </ul>
            <div class="tab-content">
              <div id="Individual" class="tab-pane fade in active">
                <form [formGroup]="personalForm" (ngSubmit)="onSubmit()">
                  <div class="row">
                    <div class="col-sm-6">
                      <div class="form-group">
                        <input class="form-control" placeholder="{{lang.FirstName}}" formControlName="first_name"
                          [ngClass]="{ 'is-invalid': submitted && pf.first_name.errors }" />
                        <div *ngIf="submitted && pf.first_name.errors" class="invalid-feedback">
                          <div *ngIf="pf.first_name.errors.required" [innerHtml]="errors.first_nameRequired"></div>
                          <div *ngIf="pf.first_name.errors.maxlength" [innerHtml]="errors.first_nameMaxLength"></div>
                        </div>
                      </div>
                    </div>
                    <div class="col-sm-6">
                      <div class="form-group">
                        <input class="form-control" placeholder="{{lang.LastName}}" formControlName="last_name"
                          [ngClass]="{ 'is-invalid': submitted && pf.last_name.errors }" />
                        <div *ngIf="submitted && pf.last_name.errors" class="invalid-feedback">
                          <div *ngIf="pf.last_name.errors.required" [innerHtml]="errors.last_nameRequired"></div>
                          <div *ngIf="pf.last_name.errors.maxlength" [innerHtml]="errors.last_nameMaxLength"></div>
                        </div>
                      </div>
                    </div>
                    <div class="col-sm-12" *ngIf="account_type==2">
                      <div class="form-group">
                        <input class="form-control" placeholder="{{lang.CompanyName}}" formControlName="company_name"
                          [ngClass]="{ 'is-invalid': submitted && pf.company_name.errors }" />
                        <div *ngIf="submitted && pf.company_name.errors" class="invalid-feedback">
                          <div *ngIf="pf.company_name.errors.required" [innerHtml]="errors.company_nameRequired"></div>
                          <div *ngIf="pf.company_name.errors.maxlength" [innerHtml]="errors.company_nameMaxLength"></div>
                        </div>
                      </div>
                    </div>
                    <!-- <div class="col-sm-12">
                      <div class="form-group">
                        <input class="form-control" placeholder="{{lang.UserName}}" formControlName="username"
                          [ngClass]="{ 'is-invalid': submitted && pf.username.errors }" />
                        <div *ngIf="submitted && pf.username.errors" class="invalid-feedback">
                          <div *ngIf="pf.username.errors.required" [innerHtml]="errors.usernameRequired"></div>
                          <div *ngIf="pf.username.errors.maxlength" [innerHtml]="errors.usernameRange"></div>
                          <div *ngIf="pf.username.errors.minlength" [innerHtml]="errors.usernameRange"></div>
                          <div *ngIf="pf.username.errors.pattern" [innerHtml]="errors.usernamePattern"></div>
                        </div>
                      </div>
                    </div> -->
                    <div class="col-sm-12">
                      <div class="form-group">
                        <input class="form-control" (keyup)="onEmailKeyUp($event)" placeholder="{{lang.Email}}"
                          formControlName="email" [ngClass]="{ 'is-invalid': (submitted && pf.email.errors) || invalidEmail }">
                        <div *ngIf="submitted && pf.email.errors" class="invalid-feedback">
                          <div *ngIf="pf.email.errors.required" [innerHtml]="errors.emailRequired"></div>
                          <div *ngIf="pf.email.errors.maxlength" [innerHtml]="errors.emailMaxLength"></div>
                        </div>
                        <div *ngIf="submitted && (invalidEmail || pf.email.errors)" class="invalid-feedback">
                          <div *ngIf="!pf.email.errors; else autoEmailInvalid" [innerHtml]="errors.emailInvalid"></div>
                          <ng-template #autoEmailInvalid>
                            <div *ngIf="pf.email.errors.email" [innerHtml]="errors.emailInvalid"></div>
                          </ng-template>
                        </div>
                      </div>
                    </div>
                    <div class="col-sm-12">
                      <div class="form-group">
                        <input type="password" class="form-control" (keyup)="matchPassword($event)" placeholder="{{lang.Password}}"
                          formControlName="password" [ngClass]="{ 'is-invalid': submitted && pf.password.errors }" />
                        <div *ngIf="submitted && pf.password.errors" class="invalid-feedback">
                          <div *ngIf="pf.password.errors.required" [innerHtml]="errors.passwordRequired"></div>
                          <div *ngIf="pf.password.errors.pattern" [innerHtml]="errors.passwordPattern"></div>
                        </div>
                      </div>
                    </div>
                    <div class="col-sm-12">
                      <div class="form-group">
                        <input type="password" class="form-control" (keyup)="matchPassword($event)" placeholder="{{lang.ConfirmPassword}}"
                          formControlName="confirm_password" [ngClass]="{ 'is-invalid': submitted && pf.confirm_password.errors }" />
                        <div *ngIf="submitted && pf.confirm_password.errors" class="invalid-feedback">
                          <div [innerHtml]="errors.passwordDidNotMatch"></div>
                        </div>
                      </div>
                    </div>

                    <div class="col-sm-12" *ngIf="!globals.isDev">
                      <div class="form-group">
                        <re-captcha class="no-form-control" formControlName="personal_capitcha" (scriptLoad)="onScriptLoad()" (scriptError)="onScriptError()"
                        [ngClass]="{ 'is-invalid': submitted && pf.personal_capitcha.status != 'VALID' }">
                        </re-captcha>
                        <div *ngIf="submitted && pf.personal_capitcha.status != 'VALID'" class="invalid-feedback">
                          <div [innerHtml]="errors.capitchaErrorMessage"></div>
                        </div>
                      </div>
                    </div>
                    <div class="col-sm-12 order-txt">
                      "In order to be GDPR compliant, you give permission to us for using
                      your
                      personal data on our servers."
                    </div>
                    <div class="col-sm-12 form-group">
                      <button class="signup-btn btn-primary" [disabled]="diableSubmitButton">CREATE ACCOUNT</button>
                    </div>
                    <div class="col-sm-12">
                      <strong>
                        <div class="{{submitRequestResposneClass}} text-bold" *ngIf="showsubmitResponse" [innerHtml]="submitResponseMessage"></div>
                      </strong>
                    </div>

                  </div>
                </form>
              </div>
            </div>
          </div>
          <div class="pstylish color-white">
              <span [innerHTML]="lang.AlreadyHaveAnAccount"></span>
              <a class="hyperlink-color" [routerLink]="'/' + constants.RoutePaths.Login" [innerHTML]="lang.Login"></a> 
            </div>
        </div>

      </div>
    </div>
  </section>
</div>

// client/src/app/components/account/SignUpComponent.tsx
import { BaseComponent } from "../base/BaseComponent";
import * as React from "react";
import { Link } from "react-router-dom";
import { StaticHelper } from "../../../shared/static-helper";
import { mdFormControl } from "../../../shared/form-control";
import { mdSignUp, SignUpMetaData } from "../../../models/sign-up";
import * as ValidationAttributes from "../../../shared/validation-attributes";
import { mdCallResponse } from "../../../models/call-response";
import { Form, Tabs, Button, Row } from "antd";
import { AccountTypes } from "../../../enums/general";
const FormItem = Form.Item;
const TabPane = Tabs.TabPane;

export default class SignUpComponent extends BaseComponent {
  render() {
    this.initShorts();
    let formItems = () => {
      return (
        <Form
          onSubmit={this.onSubmit}
          className="gx-login-form gx-form-row0"
          style={{ maxWidth: "unset" }}
        >
          <Row>
            {this.antd.colmd12(
              this.antd.textFormItem(this.f.first_name, false),
              true,
              false
            )}
            {this.antd.colmd12(
              this.antd.textFormItem(this.f.last_name, false),
              false,
              true
            )}
          </Row>
          {/* {
            this.textFormItem(this.f.first_name, false)
          }
          {
            this.textFormItem(this.f.last_name, false)
          } */}
          {this.state.account_type == AccountTypes.Business
            ? this.antd.textFormItem(this.f.company_name, false)
            : null}
          {this.antd.textFormItem(this.f.email, false)}
          <Row>
            {this.antd.colmd12(
              this.antd.passwordFormItem(this.f.password, false),
              true,
              false
            )}
            {this.antd.colmd12(
              this.antd.passwordFormItem(this.f.confirm_password, false),
              false,
              true
            )}
          </Row>
          {/* {
            this.passwordFormItem(this.f.password, false)
          }
          {
            this.passwordFormItem(this.f.confirm_password, false)
          } */}
          {this.antd.checkboxFormItem(
            this.f.agreement,
            false,
            null,
            <>
              {this.lang.IAgree}
              &nbsp;
              <Link
                className="gx-login-form-forgot"
                to={this.getLink(this.constants.RoutePaths.Home)}
              >
                {this.lang.TermsOfUse}
              </Link>
            </>
          )}
          <Button
            loading={this.state.disableSubmitButton}
            type="primary"
            htmlType="submit"
            disabled={this.state.disableSubmitButton}
            className="gx-w-100"
          >
            {this.lang.CreateAccount}
          </Button>
        </Form>
      );
    };
    return (
      <>
        <div className="gx-text-center">
          <img
            className="gx-mt-2"
            src="/assets/images/footer-logo.png"
            width={180}
            height={88}
          />
        </div>
        <div
          className="gx-login-container"
          style={{ overflow: "auto", paddingBottom: "120px" }}
        >
          <div className="gx-login-content" style={{ maxWidth: "500px" }}>
            <div className="gx-login-header gx-text-center">
              <h1 className="gx-login-title">{this.lang.CreateAccount}</h1>
            </div>
            <Tabs
              defaultActiveKey={AccountTypes.Individual.toString()}
              onChange={(e: AccountTypes) => {
                this.signupType(e);
              }}
            >
              <TabPane
                tab={
                  <>
                    <img src="/assets/images/u-icon.png" alt="Individual" />
                    &nbsp;
                    {this.lang.Individual}
                  </>
                }
                key={AccountTypes.Individual}
              >
                {formItems()}
              </TabPane>
              <TabPane
                tab={
                  <>
                    <img
                      src="/assets/images/b-icon.png"
                      alt={this.lang.Business}
                    />
                    &nbsp;
                    {this.lang.Business}
                  </>
                }
                key={AccountTypes.Business}
              >
                {formItems()}
              </TabPane>
            </Tabs>
            <div className="gx-flex-row">
              <span className="gx-mb-2 gx-mr-3">
                {this.lang.AlreadyHaveAnAccount}
              </span>
              <Link to={this.getLink(this.constants.RoutePaths.Login)}>
                {this.lang.Login}
              </Link>
            </div>
          </div>
        </div>
      </>
    );
  }

  model: mdSignUp;
  passwordDidNotMatch: boolean;
  constructor(props) {
    super(props);
    this.init();
  }

  init() {
    this.passwordDidNotMatch = true;
    this.model = new mdSignUp(true);
    this.state = {
      ...this.state,
      form: {
        first_name: new mdFormControl(
          this.model.first_name,
          "first_name",
          this.lang.FirstName,
          [
            new ValidationAttributes.RequiredValidator(
              this.lang.RequiredFormat
            ),
            new ValidationAttributes.MaxLengthValidator(
              this.lang.MaxLengthFormat2,
              SignUpMetaData.firstNameMaxLength
            )
          ],
          "user"
        ),
        last_name: new mdFormControl(
          this.model.last_name,
          "last_name",
          this.lang.LastName,
          [
            new ValidationAttributes.RequiredValidator(
              this.lang.RequiredFormat
            ),
            new ValidationAttributes.MaxLengthValidator(
              this.lang.MaxLengthFormat2,
              SignUpMetaData.lastNameMaxLength
            )
          ],
          "user"
        ),
        company_name: new mdFormControl(
          this.model.company_name,
          "company_name",
          this.lang.CompanyName,
          [],
          "briefcase"
        ),
        email: new mdFormControl(
          this.model.email,
          "email",
          this.lang.Email,
          [
            new ValidationAttributes.MailValidator(this.lang.InvalidEmail),
            new ValidationAttributes.MaxLengthValidator(
              this.lang.MaxLengthFormat2,
              SignUpMetaData.emailMaxLength
            )
          ],
          "envelope"
        ),
        password: new mdFormControl(
          this.model.password,
          "password",
          this.lang.Password,
          [
            // new ValidationAttributes.RequiredValidator(this.lang.RequiredFormat),
            new ValidationAttributes.RegexValidator( //length rage
              StaticHelper.formatString(
                this.constants.Regex.RangeLength,
                SignUpMetaData.passwordMinLength,
                SignUpMetaData.passwordMaxLength
              ),
              this.lang.RangeLengthFormat2,
              SignUpMetaData.passwordMinLength,
              SignUpMetaData.passwordMaxLength
            ),
            new ValidationAttributes.RegexValidator(
              this.constants.Regex.MustContainSmallLetter, //must contain small letter
              this.lang.MustContainOneSmallLetterFormat
            ),
            new ValidationAttributes.RegexValidator(
              this.constants.Regex.MustContainCapitalLetter, //must contain capital letter
              this.lang.MustContainOneCapitalLetterFormat
            ),
            new ValidationAttributes.RegexValidator(
              this.constants.Regex.MustContainSpecialChar, //special char
              this.lang.MustContainOneSpecialCharFormat
            ),
            new ValidationAttributes.RegexValidator(
              this.constants.Regex.MustContainNumber, //number
              this.lang.MustContainOneNumberFormat
            )
            // new ValidationAttributes.RegexValidator(this.lang.PasswordRequirement, SignUpMetaData.passwordRegex, this.lang.Password, SignUpMetaData.passwordMinLength,
            //   SignUpMetaData.passwordMaxLength)
          ],
          "lock"
        ),
        confirm_password: new mdFormControl(
          this.model.confirm_password,
          "confirm_password",
          this.lang.ConfirmPassword,
          [],
          "lock"
        ),
        agreement: new mdFormControl(0, "agreement", this.lang.TermsOfUse, [
          new ValidationAttributes.RegexpValidator(
            this.lang.RequiredFormat,
            new RegExp("true")
          )
        ])
        // captcha: global.isDev ? null : new mdFormControl(null, "captcha", '', [
        //     new ValidationAttributes.RequiredValidator(this.lang.CapitchaErrorMessage)
        // ])
      },
      disableSubmitButton: false,
      showSubmitResponse: false,
      submitResponseClass: "text-danger",
      submitResponse: "",
      account_type: AccountTypes.Individual
    };
  }

  signupType = (type: AccountTypes) => {
    let company_name = this.state.form.company_name as mdFormControl;
    if (type == AccountTypes.Individual) {
      company_name.validators = null;
    } else {
      company_name.validators = [
        new ValidationAttributes.RequiredValidator(this.lang.RequiredFormat),
        new ValidationAttributes.MaxLengthValidator(
          this.lang.MaxLengthFormat2,
          SignUpMetaData.companyNameMaxLength
        )
      ];
    }
    this.updateState({
      form: {
        ...this.state.form,
        company_name
      },
      account_type: type
    });
  };

  matchPassword = (ev: any) => {
    if (this.showErrors) {
      if (
        this.state.form.password.value ===
        this.state.form.confirm_password.value
      ) {
        this.passwordDidNotMatch = false;
      } else {
        this.passwordDidNotMatch = true;
        let confirm_password = this.state.form
          .confirm_password as mdFormControl;
        if (confirm_password.errors) {
          if (confirm_password.errors.length < 1) {
            confirm_password.errors = null;
          }
        }
        if (!confirm_password.errors) {
          confirm_password.errors = [
            StaticHelper.formatString(
              this.lang.DidNotMatchFormat,
              this.lang.Password,
              this.lang.ConfirmPassword
            )
          ];
          this.updateState({
            form: {
              ...this.state.form,
              confirm_password
            }
          });
        }
      }
    }
  };

  onSubmit = e => {
    e.preventDefault();
    this.showErrors = true;
    // if (this.personalForm.controls.personal_capitcha.status != "VALID" && !this.globals.isDev) {
    //     return;
    // }
    // stop here if form is invalid
    if (!this.validateForm("form")) {
      this.log.debug("invalid form");
      return;
    }

    this.matchPassword(null);
    if (this.passwordDidNotMatch) {
      return;
    }

    //everything is fine, now save the data
    this.updateState({
      submitResponse: "",
      disableSubmitButton: true
    });
    let formData: mdSignUp = this.getFormData(this.state.form) as mdSignUp;
    formData.account_type = this.state.account_type;
    formData.uuid = StaticHelper.getUUID();

    this.http
      .post<mdCallResponse>(
        this.constants.EndPoints.PostAccountRegister,
        formData
      )
      .then((res: mdCallResponse) => {
        // this.spinner.hide();
        this.log.debug(res);
        if (res) {
          if (res.isSuccess) {
            //signup completed, now sign in
            let token = res.extras.token;
            res = null;
            var newFormData = {
              username: formData.email,
              password: formData.password,
              grant_type: this.constants.GrantTypes.Password,
              captcha: token
            };
            this.http
              .post<mdCallResponse>(
                this.constants.EndPoints.PostAuthLogin,
                newFormData
              )
              .then((res: mdCallResponse) => {
                this.log.debug(res);
                if (res) {
                  if (res.isSuccess) {
                    window.location.href = this.getLink(
                      this.constants.RoutePaths.EmailConfirmation
                    ); // + "?" + this.constants.QueryParams.email + "=em";//we just need to set something in this param if we want to send email on component load
                  } else {
                    this.hideSpinnerAndShowError();
                    this.props.history.push(this.constants.RoutePaths.Login);
                  }
                } else {
                  this.hideSpinnerAndShowError(
                    this.bulletList(res.message.split("\n"))
                  );
                }
              })
              .catch(error => {
                this.log.debug(error);
                this.hideSpinnerAndShowError();
              });
          } else {
            this.errorNotification(res.message, this.lang.Error);
            this.hideSpinnerAndShowError(
              this.bulletList(res.message.split("\n"))
            );
          }
        }
      })
      .catch(error => {
        this.log.debug(error);
        this.hideSpinnerAndShowError(this.lang.UnableToCompleteYourRequest);
      });
  };

  hideSpinnerAndShowError(message = null) {
    if (!message) {
      message = this.lang.AccountCreatedLoginToContinue;
    }
    this.hideMainSpinner();
    this.updateState({
      disableSubmitButton: false,
      showSubmitResponse: true,
      submitResponse: message
    });
  }
}
