// my-app/src/app/components/contact-us/contact-us.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ValidationErrors, FormControl } from '@angular/forms';
import { mdContactUs, ContactUsMetaData } from '../../models/contact-us';
import { Constants } from '../../shared/constants';
import { LanguageBase } from '../../shared/language';
import { String } from '../../shared/strings';
import { HttpClientService } from '../../services/http-client.service';
import { SpinnerService } from '../../services/spinner.service';
import { mdCallResponse } from '../../models/call-response';
import * as EmailValidator from 'email-validator';
import { v4 as uuid } from 'uuid';
import { Router } from '@angular/router';
import { GlobalsService } from 'src/app/services/globals.service';

declare var $;

@Component({
    selector: 'app-contact-us',
    templateUrl: './contact-us.component.html',
    styleUrls: ['./contact-us.component.css']
})
export class ContactUsComponent implements OnInit {

    // constants: Constants = new Constants();
    lang: LanguageBase;
    frmContactUs: mdContactUs;
    contactUsForm: FormGroup;
    submitted = false;
    errors: any;
    submitResponseMessage: string;
    showsubmitResponse: boolean;
    submitRequestResposneClass: string;
    invalidEmail: boolean;
    diableSubmitButton: boolean;

    constructor(private formBuilder: FormBuilder, private http: HttpClientService,
        private spinner: SpinnerService, private router: Router, private globals: GlobalsService) {
    }

    ngOnInit() {
        this.lang = this.globals.lang;
        this.showsubmitResponse = false;
        this.submitResponseMessage = "";
        this.submitRequestResposneClass = "";
        this.frmContactUs = new mdContactUs(true);
        this.invalidEmail = false;
        this.diableSubmitButton = false;
        this.contactUsForm = this.formBuilder.group({
            name: [
                this.frmContactUs.name,
                Validators.compose([
                    Validators.required,
                    Validators.maxLength(ContactUsMetaData.nameMaxLength)
                ])
            ],
            contact_no: [
                this.frmContactUs.contact_no,
                Validators.compose([
                    Validators.required,
                    Validators.maxLength(ContactUsMetaData.contactNoMaxLength)
                ])
            ],
            email: [
                this.frmContactUs.email,
                Validators.compose([
                    Validators.required,
                    Validators.email,
                    Validators.maxLength(ContactUsMetaData.emailMaxLength)
                ])
            ],
            message: [
                this.frmContactUs.message,
                Validators.compose([
                    Validators.required,
                    Validators.maxLength(ContactUsMetaData.messageMaxLength)
                ])
            ],
            contactus_capitcha: new FormControl(false, null)
        });
        this.errors = {
            nameRequried: String.format(this.lang.RequiredFormat, this.lang.Name),
            nameMaxLength: String.format(this.lang.MaxLengthFormat, ContactUsMetaData.nameMaxLength),
            contactNoRequired: String.format(this.lang.RequiredFormat, this.lang.ContactNo),
            contactNoMaxLength: String.format(this.lang.MaxLengthFormat, ContactUsMetaData.contactNoMaxLength),
            emailRequried: String.format(this.lang.RequiredFormat, this.lang.Email),
            emailMaxLength: String.format(this.lang.MaxLengthFormat, ContactUsMetaData.emailMaxLength),
            emailInvalid: this.lang.InvalidEmail,
            messageRequried: String.format(this.lang.RequiredFormat, this.lang.Message),
            messageRange: String.format(this.lang.RangeLengthFormat, ContactUsMetaData.messageMinLength, ContactUsMetaData.messageMaxLength),
            capitchaErrorMessage: this.lang.CapitchaErrorMessage,
        };
    }
    // bool: any;
    // convenience getter for easy access to form fields
    get f() { return this.contactUsForm.controls; }

    onEmailKeyUp(ev: any) {
        if (this.submitted) {
            if (!EmailValidator.validate(this.contactUsForm.controls.email.value)) {
                this.invalidEmail = true;
            }
            else {
                this.invalidEmail = false;
            }
        }
    }

    onScriptLoad() {
        console.log('Google reCAPTCHA loaded and is ready for use!')
    }

    onScriptError() {
        console.log('Something went long when loading the Google reCAPTCHA')
    }

    onSubmit() {
        this.submitted = true;
        let captchaResposne = $("#g-recaptcha-response").val();
        console.log("captchaResposne: " + captchaResposne);
        if (this.contactUsForm.controls.contactus_capitcha.status != "VALID") {
            return;
        }
        // stop here if form is invalid
        if (this.contactUsForm.invalid) {
            return;
        }

        if (!EmailValidator.validate(this.contactUsForm.controls.email.value)) {
            this.invalidEmail = true;
            return;
        }
        else {
            this.invalidEmail = false;
        }

        //everything is fine, now save the data
        this.diableSubmitButton = true;
        this.invalidEmail = false;
        let formData: mdContactUs = this.contactUsForm.value;
        formData.uuid = uuid();
        let res = new mdCallResponse();
        //var response = this.http.post(this.http.endpoints.postContactUs, formData);
        this.spinner.show();
        this.http.post<mdCallResponse>(Constants.EndPoints.PostContactUs, formData).subscribe((data) => {
            res = data;
        }, (error) => {
            console.log(error);
            this.spinner.hide();
        }, () => {
            this.spinner.hide();
            this.submitRequestResposneClass = "text-danger";
            console.log(res);
            if (res) {
                this.submitResponseMessage = res.message.replace("\n", "<br/>");
                if (res.isSuccess) {
                    this.submitRequestResposneClass = "text-success";
                }
            }
            this.showsubmitResponse = true;
            setTimeout(() => {
                // this.showsubmitResponse = false;
                // this.submitRequestResposneClass = "";
                // this.submitResponseMessage = "";
                this.router.navigateByUrl('');
            }, Constants.ResponseMessageTimeout * 1000);
        });
    }

}

<div class="mainpage clearfix">
  <!-- ContactUs Start -->
  <section class="signupwrap clearfix">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3 col-sm-12 ">
          <h3>Contact Us</h3>
          <form [formGroup]="contactUsForm" (ngSubmit)="onSubmit()">
            <div class="signupbox clearfix">
              <div class="tab-content">
                <div id="Individual" class="tab-pane fade in active">
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="form-group">
                        <input class="form-control" placeholder="{{lang.Name}}" formControlName="name" [ngClass]="{ 'is-invalid': submitted && f.name.errors }" />
                        <div *ngIf="submitted && f.name.errors" class="invalid-feedback">
                          <div *ngIf="f.name.errors.required" [innerHtml]="errors.nameRequried"></div>
                          <div *ngIf="f.name.errors.maxlength" [innerHtml]="errors.nameMaxLength"></div>
                        </div>
                      </div>
                    </div>
                    <div class="col-sm-12">
                      <div class="form-group">
                        <input class="form-control" placeholder="{{lang.ContactNo}}" formControlName="contact_no"
                          [ngClass]="{ 'is-invalid': submitted && f.contact_no.errors }" />
                        <div *ngIf="submitted && f.contact_no.errors" class="invalid-feedback">
                          <div *ngIf="f.contact_no.errors.required" [innerHtml]="errors.contactNoRequired"></div>
                          <div *ngIf="f.contact_no.errors.maxlength" [innerHtml]="errors.contactNoMaxLength"></div>
                        </div>
                      </div>
                    </div>
                    <div class="col-sm-12">
                      <div class="form-group">
                        <input class="form-control" (keyup)="onEmailKeyUp($event)" placeholder="{{lang.Email}}"
                          formControlName="email" [ngClass]="{ 'is-invalid': (submitted && f.email.errors) || invalidEmail }">
                        <div *ngIf="submitted && f.email.errors" class="invalid-feedback">
                          <div *ngIf="f.email.errors.required" [innerHtml]="errors.emailRequried"></div>
                          <div *ngIf="f.email.errors.maxlength" [innerHtml]="errors.emailMaxLength"></div>
                        </div>
                        <div *ngIf="submitted && (invalidEmail || f.email.errors)" class="invalid-feedback">
                          <div *ngIf="!f.email.errors; else autoEmailInvalid" [innerHtml]="errors.emailInvalid"></div>
                          <ng-template #autoEmailInvalid>
                            <div *ngIf="f.email.errors.email" [innerHtml]="errors.emailInvalid"></div>
                          </ng-template>
                        </div>
                      </div>
                    </div>
                    <div class="col-sm-12">
                      <div class="form-group">
                        <textarea class="form-control" formControlName="message" style="height: auto !important;" rows="4"
                          placeholder="{{lang.Message}}" [ngClass]="{ 'is-invalid': submitted && f.message.errors }"></textarea>
                        <div *ngIf="submitted && f.message.errors" class="invalid-feedback">
                          <div *ngIf="f.message.errors.required" [innerHtml]="errors.messageRequried"></div>
                          <div *ngIf="f.message.errors.minlength" [innerHtml]="errors.messageRange"></div>
                          <div *ngIf="f.message.errors.maxlength" [innerHtml]="errors.messageRange"></div>
                        </div>
                      </div>
                    </div>
                    <div class="col-sm-12">
                      <div class="form-group">
                        <recaptcha 
                        class="no-form-control" 
                        formControlName="contactus_capitcha" 
                        (scriptLoad)="onScriptLoad()" 
                        (scriptError)="onScriptError()"
                        [ngClass]="{ 'is-invalid': submitted && f.contactus_capitcha.status != 'VALID' }">
                        </recaptcha>
                        <div *ngIf="submitted && f.contactus_capitcha.status != 'VALID'" class="invalid-feedback">
                          <div [innerHtml]="errors.capitchaErrorMessage"></div>
                        </div>
                      </div>
                    </div>
                    <div class="col-sm-12 form-group">
                      <button class="btn-primary signup-btn " [disabled]="diableSubmitButton" name="btn-submit"
                        [innerHtml]="lang.Submit"></button>
                    </div>
                    <div class="col-sm-12">
                      <strong>
                        <div class="{{submitRequestResposneClass}} text-bold" *ngIf="showsubmitResponse" [innerHtml]="submitResponseMessage"></div>
                      </strong>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
</div>
<script>


</script>

// client/src/app/components/contact-us/ContactUsComponent.tsx
import React = require('react');
import { LanguageBase } from '../../../shared/language';
import { mdContactUs, ContactUsMetaData } from '../../../models/contact-us';
import { mdProps } from '../../../models/props';
import { Constants } from '../../../shared/constants';
import { StaticHelper } from '../../../shared/static-helper';
import * as ValidationAttributes from "../../../shared/validation-attributes"
import { mdFormControl } from '../../../shared/form-control';
import { mdCallResponse } from '../../../models/call-response';
import { BaseComponent } from '../base/BaseComponent';


export default class ContactUsComponent extends BaseComponent {

    render() {
        this.initShorts();
        return (
            <div className="mainpage clearfix">
                <section className="signupwrap clearfix">
                    <div className="container">
                        <div className="row">
                            <div className="col-md-6 col-md-offset-3 col-sm-12 ">
                                <p className="h3">{this.lang.ContactUs}</p>
                                <form onSubmit={this.onSubmit}>
                                    <div className="signupbox clearfix">
                                        <div className="tab-content">
                                            <div id="Individual" className="tab-pane fade in active">
                                                <div className="row">
                                                    <div className="col-sm-12">
                                                        {
                                                            this.textFormControl(this.f.name, this.handleFormControlInput)
                                                        }
                                                    </div>
                                                    <div className="col-sm-12">
                                                        {
                                                            this.textFormControl(this.f.contact_no, this.handleFormControlInput)
                                                        }
                                                    </div>
                                                    <div className="col-sm-12">
                                                        {
                                                            this.textFormControl(this.f.email, this.handleFormControlInput)
                                                        }
                                                    </div>
                                                    <div className="col-sm-12">
                                                        {
                                                            this.textareaFormControl(this.f.message, this.handleFormControlInput)
                                                        }
                                                    </div >
                                                    <div className="col-sm-12 form-group">
                                                        <button type="submit" className="btn-primary signup-btn " disabled={this.f.diableSubmitButton} >{this.lang.Submit}</button>
                                                    </div >
                                                    <div className="col-sm-12">
                                                        {
                                                            this.getSubmitResponseDiv(this.f.submitResponseClass,
                                                                this.f.submitResponse, this.f.showSubmitResponse)
                                                        }
                                                    </div >
                                                </div >
                                            </div >
                                        </div >
                                    </div >
                                </form >
                            </div >
                        </div >
                    </div >
                </section >
            </div >
        );
    }

    model: mdContactUs;
    showErrors: boolean;

    constructor(props) {
        super(props);
        this.init();
    }

    init() {
        this.model = new mdContactUs(true);
        this.state = {
            form: {
                name: new mdFormControl(this.model.name, "name", this.lang.Name, [
                    new ValidationAttributes.RequiredValidator(this.lang.RequiredFormat),
                    new ValidationAttributes.MaxLengthValidator(this.lang.MaxLengthFormat2,
                        ContactUsMetaData.nameMaxLength),
                ]),
                contact_no: new mdFormControl(this.model.contact_no, "contact_no", this.lang.ContactNo, [
                    new ValidationAttributes.RequiredValidator(this.lang.RequiredFormat),
                    new ValidationAttributes.MaxLengthValidator(this.lang.MaxLengthFormat2,
                        ContactUsMetaData.contactNoMaxLength),
                ]),
                email: new mdFormControl(this.model.email, "email", this.lang.Email, [
                    new ValidationAttributes.MailValidator(this.lang.InvalidEmail),
                    new ValidationAttributes.MaxLengthValidator(this.lang.MaxLengthFormat2,
                        ContactUsMetaData.emailMaxLength),
                ]),
                message: new mdFormControl(this.model.message, "message", this.lang.Message, [
                    new ValidationAttributes.RequiredValidator(this.lang.RequiredFormat),
                    new ValidationAttributes.MaxLengthValidator(this.lang.MaxLengthFormat2,
                        ContactUsMetaData.messageMaxLength),
                ]),
                diableSubmitButton: false,
                showSubmitResponse: false,
                submitResponseClass: '',
                submitResponse: '',
            },
        }
    }

    onSubmit = (e) => {
        e.preventDefault();
        this.showErrors = true;
        // stop here if form is invalid

        if (!this.validateForm('form')) {
            this.log.debug("invalid form");
            return;
        }

        //everything is fine, now save the data
        this.props.updateGlobalProperty(global.propKeys.showMainLoader, true);
        this.updateState({ form: { ...this.state.form, diableSubmitButton: true } });
        let formData: mdContactUs = this.getFormData(this.state.form) as mdContactUs;
        formData.uuid = StaticHelper.getUUID();

        this.http.post(this.constants.EndPoints.PostContactUs, formData).then((res: mdCallResponse) => {
            let submitResponseClass = "text-danger";
            let submitResponse = '';
            if (res) {
                submitResponse = res.message.replace("\n", "<br/>");
                if (res.isSuccess) {
                    submitResponseClass = "text-success";
                }
            }

            this.updateState({
                form: {
                    ...this.state.form,
                    showSubmitResponse: true,
                    submitResponseClass: submitResponseClass,
                    submitResponse: submitResponse,
                }
            })
            setTimeout(() => {
                this.props.history.push(this.constants.RoutePaths.Home);
            }, this.constants.ResponseMessageTimeout * 1000);
            this.props.updateGlobalProperty(global.propKeys.showMainLoader, false);
        }).catch((error) => {
            this.log.debug(error);
            this.props.updateGlobalProperty(global.propKeys.showMainLoader, false);
        });
    }

}
