// client/src/app/components/contact-us/contact-us.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ValidationErrors, FormControl } from '@angular/forms';
import { mdContactUs, ContactUsMetaData } from '../../models/contact-us';
import { LanguageBase } from '../../shared/language';
import { HttpClientService } from '../../services/http-client.service';
import { SpinnerService } from '../../services/spinner.service';
import { mdCallResponse } from '../../models/call-response';
import * as EmailValidator from 'email-validator';
import { v4 as uuid } from 'uuid';
import { Router } from '@angular/router';
import { GlobalsService } from 'src/app/services/globals.service';
import { StaticHelper } from 'src/app/shared/static-helper';
import { Constants } from '../../shared/constants';

declare var $;

@Component({
    selector: 'app-contact-us',
    templateUrl: './contact-us.component.html',
    styleUrls: []
})
export class ContactUsComponent implements OnInit {

    // constants: Constants = new Constants();
    lang: LanguageBase;
    frmContactUs: mdContactUs;
    contactUsForm: FormGroup;
    submitted = false;
    errors: any;
    submitResponseMessage: string;
    showsubmitResponse: boolean;
    submitRequestResposneClass: string;
    invalidEmail: boolean;
    diableSubmitButton: boolean;
    constants: Constants;

    constructor(private formBuilder: FormBuilder, 
        private http: HttpClientService,
        private spinner: SpinnerService, 
        private router: Router, 
        public globals: GlobalsService) {
    }

    ngOnInit() {
        this.constants = this.globals.constants;
        this.lang = this.globals.lang;
        this.showsubmitResponse = false;
        this.submitResponseMessage = "";
        this.submitRequestResposneClass = "";
        this.frmContactUs = new mdContactUs(true);
        this.invalidEmail = false;
        this.diableSubmitButton = false;
        this.contactUsForm = this.formBuilder.group({
            name: [
                this.frmContactUs.name,
                Validators.compose([
                    Validators.required,
                    Validators.maxLength(ContactUsMetaData.nameMaxLength)
                ])
            ],
            contact_no: [
                this.frmContactUs.contact_no,
                Validators.compose([
                    Validators.required,
                    Validators.maxLength(ContactUsMetaData.contactNoMaxLength)
                ])
            ],
            email: [
                this.frmContactUs.email,
                Validators.compose([
                    Validators.required,
                    Validators.email,
                    Validators.maxLength(ContactUsMetaData.emailMaxLength)
                ])
            ],
            message: [
                this.frmContactUs.message,
                Validators.compose([
                    Validators.required,
                    Validators.maxLength(ContactUsMetaData.messageMaxLength)
                ])
            ],
            contactus_capitcha: new FormControl(false, null)
        });
        this.errors = {
            nameRequried: StaticHelper.formatString(this.lang.RequiredFormat, this.lang.Name),
            nameMaxLength: StaticHelper.formatString(this.lang.MaxLengthFormat, ContactUsMetaData.nameMaxLength),
            contactNoRequired: StaticHelper.formatString(this.lang.RequiredFormat, this.lang.ContactNo),
            contactNoMaxLength: StaticHelper.formatString(this.lang.MaxLengthFormat, ContactUsMetaData.contactNoMaxLength),
            emailRequried: StaticHelper.formatString(this.lang.RequiredFormat, this.lang.Email),
            emailMaxLength: StaticHelper.formatString(this.lang.MaxLengthFormat, ContactUsMetaData.emailMaxLength),
            emailInvalid: this.lang.InvalidEmail,
            messageRequried: StaticHelper.formatString(this.lang.RequiredFormat, this.lang.Message),
            messageRange: StaticHelper.formatString(this.lang.RangeLengthFormat, ContactUsMetaData.messageMinLength, ContactUsMetaData.messageMaxLength),
            capitchaErrorMessage: this.lang.CapitchaErrorMessage,
        };
    }
    // bool: any;
    // convenience getter for easy access to form fields
    get f() { return this.contactUsForm.controls; }

    onEmailKeyUp(ev: any) {
        if (this.submitted) {
            if (!EmailValidator.validate(this.contactUsForm.controls.email.value)) {
                this.invalidEmail = true;
            }
            else {
                this.invalidEmail = false;
            }
        }
    }

    onScriptLoad() {
        console.log('Google reCAPTCHA loaded and is ready for use!')
    }

    onScriptError() {
        console.log('Something went long when loading the Google reCAPTCHA')
    }

    onSubmit() {
        this.submitted = true;
        let captchaResposne = $("#g-recaptcha-response").val();
        console.log("captchaResposne: " + captchaResposne);
        if (this.contactUsForm.controls.contactus_capitcha.status != "VALID") {
            return;
        }
        // stop here if form is invalid
        if (this.contactUsForm.invalid) {
            return;
        }

        if (!EmailValidator.validate(this.contactUsForm.controls.email.value)) {
            this.invalidEmail = true;
            return;
        }
        else {
            this.invalidEmail = false;
        }

        //everything is fine, now save the data
        this.diableSubmitButton = true;
        this.invalidEmail = false;
        let formData: mdContactUs = this.contactUsForm.value;
        formData.uuid = uuid();
        let res = new mdCallResponse();
        //var response = this.http.post(this.http.endpoints.postContactUs, formData);
        this.spinner.show();
        this.http.post<mdCallResponse>(this.constants.EndPoints.PostContactUs, formData).subscribe((data) => {
            res = data;
        }, (error) => {
            console.log(error);
            this.spinner.hide();
        }, () => {
            this.spinner.hide();
            this.submitRequestResposneClass = "text-danger";
            console.log(res);
            if (res) {
                this.submitResponseMessage = res.message.replace("\n", "<br/>");
                if (res.isSuccess) {
                    this.submitRequestResposneClass = "text-success";
                }
            }
            this.showsubmitResponse = true;
            setTimeout(() => {
                // this.showsubmitResponse = false;
                // this.submitRequestResposneClass = "";
                // this.submitResponseMessage = "";
                this.router.navigateByUrl('');
            }, this.constants.ResponseMessageTimeout * 1000);
        });
    }

}

// client/src/app/components/contact-us/ContactUs.tsx
import React from "react";
import { mdContactUs, ContactUsMetaData } from "../../../models/contact-us";
import { StaticHelper } from "../../../shared/static-helper";
import { mdFormControl } from "../../../shared/form-control";
import { mdCallResponse } from "../../../models/call-response";
import { BaseComponent } from "../base/BaseComponent";
import { Row, Card, Form, Button } from "antd";
import {
  RequiredValidator,
  MaxLengthValidator,
  MailValidator
} from "../../../shared/validation-attributes";

export default class ContactUsComponent extends BaseComponent {
  render() {
    this.initShorts();
    return (
      <Row className="full-width-controls" style={{ display: "flex" }}>
        {this.antd.colmd6(<></>)}
        {this.antd.colmd12(
          <Card
            className="gx-card form-header"
            style={{ fontSize: 25, textAlign: "center" }}
          >
            <p className="text-medium">{this.p.title || this.lang.ContactUs}</p>
            <Form
              onSubmit={this.onSubmit}
              className="gx-signin-form gx-form-row0 large-size-form"
            >
              {this.antd.textFormItem(this.f.name, false)}
              {this.antd.textFormItem(this.f.contact_no, false)}
              {this.antd.textFormItem(this.f.email, false)}
              {this.antd.textAreaFormItem(this.f.message, 4, false)}
              <div className="gx-text-center">
                <Button
                  loading={this.state.disableSubmitButton}
                  type={"primary"}
                  htmlType="submit"
                  className="gx-w-50"
                >
                  {this.lang.Submit}
                </Button>
              </div>
            </Form>
          </Card>
        )}
        {this.antd.colmd6(<></>)}
      </Row>
    );
  }

  model: mdContactUs;
  showErrors: boolean;

  constructor(props) {
    super(props);
    this.init();
  }

  init() {
    this.model = new mdContactUs(true);
    this.state = {
      form: {
        name: new mdFormControl(this.model.name, "name", this.lang.Name, [
          new RequiredValidator(this.lang.RequiredFormat),
          new MaxLengthValidator(
            this.lang.MaxLengthFormat2,
            ContactUsMetaData.nameMaxLength
          )
        ]),
        contact_no: new mdFormControl(
          this.model.contact_no,
          "contact_no",
          this.lang.ContactNo,
          [
            new RequiredValidator(this.lang.RequiredFormat),
            new MaxLengthValidator(
              this.lang.MaxLengthFormat2,
              ContactUsMetaData.contactNoMaxLength
            )
          ]
        ),
        email: new mdFormControl(this.model.email, "email", this.lang.Email, [
          new MailValidator(this.lang.InvalidEmail),
          new MaxLengthValidator(
            this.lang.MaxLengthFormat2,
            ContactUsMetaData.emailMaxLength
          )
        ]),
        message: new mdFormControl(
          this.model.message,
          "message",
          this.lang.Message,
          [
            new RequiredValidator(this.lang.RequiredFormat),
            new MaxLengthValidator(
              this.lang.MaxLengthFormat2,
              ContactUsMetaData.messageMaxLength
            )
          ]
        )
      },
      disableSubmitButton: false,
      showSubmitResponse: false,
      submitResponseClass: "",
      submitResponse: ""
    };
  }

  onSubmit = e => {
    e.preventDefault();
    this.showErrors = true;
    // stop here if form is invalid

    if (!this.validateForm("form")) {
      this.log.debug("invalid form");
      return;
    }

    //everything is fine, now save the data
    this.props.updateGlobalProperty(global.propKeys.showMainLoader, true);
    this.updateState({
      form: { ...this.state.form },
      disableSubmitButton: true
    });
    let formData: mdContactUs = this.getFormData(
      this.state.form
    ) as mdContactUs;
    formData.uuid = StaticHelper.getUUID();

    this.http
      .post(this.constants.EndPoints.PostContactUs, formData)
      .then((res: mdCallResponse) => {
        let submitResponseClass = "text-danger";
        let submitResponse = "";
        if (res) {
          submitResponse = res.message.replace("\n", "<br/>");
          if (res.isSuccess) {
            this.successNotification(res.message);
          } else {
            this.errorNotification(res.message);
          }
        } else {
          this.errorNotification(this.lang.ErrorOccured);
        }

        this.updateState({
          form: {
            ...this.state.form,
            showSubmitResponse: true,
            submitResponseClass: submitResponseClass,
            submitResponse: submitResponse
          }
        });
        setTimeout(() => {
          this.props.history.push(this.constants.RoutePaths.Home);
        }, this.constants.ResponseMessageTimeout * 1000);
        this.props.updateGlobalProperty(global.propKeys.showMainLoader, false);
      })
      .catch(error => {
        this.log.debug(error);
        this.props.updateGlobalProperty(global.propKeys.showMainLoader, false);
      });
  };
}
