// client/src/modules/searchable-dropdown/searchable-dropdown.component.ts
import { Component, Input, Output, SimpleChanges } from '@angular/core';
import { Injectable } from '@angular/core';
import { Router } from '@angular/router';
import { LanguageBase } from 'src/shared/language';
import { GlobalsService } from 'src/services/globals.service';
import { SearchableDropdownSettings } from './searchable-dropdown-settings';
import { FormBuilder, FormGroup } from '@angular/forms';
import * as $ from 'jquery';
import { EventEmitter } from '@angular/core';

@Component({
    selector: 'searchable-dropdown',
    templateUrl: './searchable-dropdown.component.html',
    styleUrls: ['./searchable-dropdown.component.css']
})

export class SearchableDropdownComponent {

    @Input() source: any;
    @Input() settings: SearchableDropdownSettings;
    @Input() selectedValue: any;
    @Input() showSpinner: boolean = false;
    @Output() change = new EventEmitter<any>();
    appliedSource: any[];
    form: FormGroup;
    buttonText: string;
    constructor(
        private formBuilder: FormBuilder,
    ) {
        this.settings = new SearchableDropdownSettings();
        this.buttonText = this.settings.placeholder;
        this.form = this.formBuilder.group({
            searchText: ['', null],
        });
    }

    get f() {
        return this.form.controls;
    }

    ngOnChanges(changes: SimpleChanges) {
        this.source = changes.source.currentValue;
        if (changes.settings) {
            if (changes.settings.currentValue != null) {
                this.settings.setSettings(changes.settings.currentValue);
                if (!this.selectedValue) {
                    this.buttonText = this.settings.placeholder;
                }
            }
        }
        if (changes.selectedValue) {
            if (changes.selectedValue != null) {
                this.selectedValue = changes.selectedValue.currentValue;
            }
        }
        if (changes.showSpinner) {
            if (changes.showSpinner != null) {
                this.showSpinner = changes.showSpinner.currentValue;
            }
        }
        this.applySearch();
    }

    ngOnInit() {
        $(".dropdown-menu").find('input').click(function (e) {
            e.stopPropagation();
        });
    }

    selectionChanged(value) {
        if (this.selectedValue != value) {
            this.change.emit({ newValue: value, previousValue: this.selectedValue });
        }
        this.selectedValue = value;
    }

    applySearch() {
        let st = '';
        if (this.f.searchText.value != null) {
            st = this.f.searchText.value;
        }

        if (st != '') {
            if (this.settings.searchCaseSensitive) {
                this.appliedSource = this.source.filter(m => m.text == st);
            }
            else {
                st = st.toUpperCase();
                this.appliedSource = this.source.filter(m => m.text.toUpperCase().indexOf(st) > -1);
            }
        }
        else {
            this.appliedSource = this.source;
        }
    }

    preventDefaultForAnchor = (event) => {
        alert(JSON.stringify(event));
        event.preventDefault();
    }

    dropdownButtonClicked() {
        this.form.controls.searchText.setValue('');
    }

}

<div class="dropdown dropdown-scroll sadd" [nbSpinner]="showSpinner">
    <button (click)="dropdownButtonClicked()" style="text-align: left;width:100%" class="btn btn-default dropdown-toggle"
        type="button" id="dropdownMenu1" data-toggle="dropdown">
        <table width="100%">
            <tr [style.height]="settings.imageHeight + 'px'">
                <td style="vertical-align:middle">
                    <span *ngIf="selectedValue == null; else setSelectedValue" [innerHTML]="buttonText"></span>
                    <ng-template #setSelectedValue>
                        <span>
                            <img *ngIf="settings.image" [width]="settings.imageWidth" [height]="settings.imageHeight"
                                [src]="selectedValue.image" />
                            {{selectedValue.text}}
                        </span>
                    </ng-template>
                </td>
                <td style="vertical-align:middle; text-align:right">
                    &nbsp;
                    <img src="assets/images/up-down-arrow.png" />
                </td>
            </tr>
        </table>
    </button>
    <ul style="width:100%" class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
        <li *ngIf="settings.searchable" role="presentation">
            <div class="input-group input-group-sm search-control">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-search"></span>
                </span>
                <form [formGroup]="form">
                    <input formControlName="searchText" type="text" class="form-control" [placeholder]="settings.searchBoxPlaceholder"
                        (input)="applySearch()">
                </form>
            </div>
        </li>
        <li role="presentation" *ngFor='let s of appliedSource' (click)="selectionChanged(s)">
            <a>
                <img *ngIf="settings.image" [width]="settings.imageWidth" [height]="settings.imageHeight" [src]="s.image" />
                {{s.text}}
            </a>
        </li>
    </ul>
</div>

// client/src/modules/shared/searchable-dropdown/SearchableDropdownComponent.tsx
import * as React from "react";
import { mdFormControl } from "../../../shared/form-control";
import { BaseComponent } from "../../../app/components/base/BaseComponent";
import "./searchable-dropdown.component.css";
import NBSpinnerComponent from "../spinner/NBSpinnerComponent";

export default class SearchableDropdownComponent extends BaseComponent {

    render() {
        this.initShorts();
        this.recievedNewChanges();
        return (
            <div className="dropdown dropdown-scroll sadd">
                <button
                    onClick={this.dropdownButtonClicked}
                    style={{ textAlign: 'left', width: '100%' }}
                    className="btn btn-default dropdown-toggle"
                    type="button"
                    id="dropdownMenu1"
                    data-toggle="dropdown">
                    <table className="col-md-12">
                        <tbody>
                            <tr style={{ height: this.p.settings.imageHeight + 'px' }}>
                                <td style={{ verticalAlign: 'middle' }}>
                                    {
                                        this.state.selectedValue == null ? (
                                            <span>{this.state.buttonText}</span>
                                        ) : (
                                                <span>
                                                    {
                                                        this.p.settings.image ? (
                                                            <img width={this.p.settings.imageWidth} height={this.p.settings.imageHeight}
                                                                src={this.state.selectedValue.image} />) : (null)
                                                    }
                                                    &nbsp;{this.state.selectedValue.text}
                                                </span>
                                            )
                                    }
                                </td>
                                <td style={{ verticalAlign: 'middle', textAlign: 'right' }}>
                                    &nbsp;
                                <img src="assets/images/up-down-arrow.png" />
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </button>
                <ul className="dropdown-menu col-md-12" role="menu" aria-labelledby="dropdownMenu1">
                    {
                        this.p.settings.searchable ? (
                            <li role="presentation">
                                <div className="input-group input-group-sm search-control">
                                    <span className="input-group-addon">
                                        <span className="glyphicon glyphicon-search"></span>
                                    </span>
                                    {
                                        this.textFormControl(this.f.searchText, [this.handleFormControlInput, this.applySearch])
                                    }

                                </div>
                            </li>) : (null)
                    }
                    {
                        this.state.appliedSource ? this.state.appliedSource.map((s, i) => {
                            return (
                                <li key={i} role="presentation" onClick={(e) => { this.selectionChanged(s) }}>
                                    <a>
                                        {
                                            this.p.settings.image ? (
                                                <img width={this.p.settings.imageWidth} height={this.p.settings.imageHeight} src={s.image} />
                                            ) : (null)
                                        }
                                        &nbsp;{s.text}
                                    </a>
                                </li>)
                        }) : null
                    }
                </ul>
                <NBSpinnerComponent {...this.props} params={{ show: this.p.showSpinner }} />
            </div>
        );
    }

    constructor(props) {
        super(props);
        this.init();
    }

    init() {
        this.state = {
            form: {
                searchText: new mdFormControl('', 'searchText', this.p.settings.searchBoxPlaceholder),
            },
            selectedValue: null,
            appliedSource: null,
            buttonText: this.p.settings.placeholder,
            showSpinner: false,
        }
    }

    recievedNewChanges() {
        this.state = {
            ...this.state,
            showSpinner: this.p.showSpinner,
            buttonText: this.state.selectedValue ? this.state.buttonText : this.p.settings.placeholder,
        }
        // if (changes.settings) {
        //     if (changes.settings.currentValue != null) {
        //         this.settings.setSettings(changes.settings.currentValue);
        //     }
        // }
        // if (changes.selectedValue != null) {
        //     state = {
        //         ...this.state,
        //         selectedValue
        //     }
        //     this.selectedValue = changes.selectedValue.currentValue;
        // }
        // if (changes.selectedValue) {
        //     if (changes.selectedValue != null) {
        //         this.selectedValue = changes.selectedValue.currentValue;
        //     }
        // }
        // if (changes.showSpinner) {
        //     if (changes.showSpinner != null) {
        //         this.showSpinner = changes.showSpinner.currentValue;
        //     }
        // }
        this.applySearch(null);
    }

    selectionChanged(value) {
        if (this.state.selectedValue != value) {
            this.p.onChange({ newValue: value, previousValue: this.state.selectedValue });
        }
        this.updateState({
            selectedValue: value
        }, () => {
            this.log.debug(this.state.selectedValue);
        });
    }

    applySearch = (ev) => {
        let st = '';
        if (this.f.searchText.value != null) {
            st = this.f.searchText.value;
        }

        let newAppliedSource
        if (st != '') {
            if (this.p.settings.searchCaseSensitive) {
                newAppliedSource = this.p.source.filter(m => m.text == st);
            }
            else {
                st = st.toUpperCase();
                newAppliedSource = this.p.source.filter(m => m.text.toUpperCase().indexOf(st) > -1);
            }
        }
        else {
            newAppliedSource = this.p.source;
        }
        let state = {
            ...this.state,
            appliedSource: newAppliedSource,
        }
        if (ev) {
            this.updateState(state);
        }
        else {
            this.state = {
                ...state,
            }
        }
    }

    preventDefaultForAnchor = (event) => {
        alert(JSON.stringify(event));
        event.preventDefault();
    }

    dropdownButtonClicked = (e) => {
        this.updateState({
            searchText: '',
        })
    }

}
