// client/src/app/components/not-found/NotFoundComponent.tsx
import * as React from "react";
import { Link } from "react-router-dom";
import { BaseComponent } from "../base/BaseComponent";
import { StaticHelper } from "../../../shared/static-helper";
import './not-found.component.css';


export default class NotFoundComponent extends BaseComponent {

    render() {
        this.initShorts();
        return (
            <div className="body signupwrap">
                <h1>{this.pageNotFoundText}></h1>
                <section className="error-container">
                    <span>4</span>
                    <span><span className="screen-reader-text">0</span></span>
                    <span>4</span>
                </section>
                <div className="link-container">
                    <Link to={this.constants.RoutePaths.Home} className="more-link">{this.lang.BackToHome}</Link>
                </div>
            </div>
        );
    }

    pageNotFoundText: string;
    constructor(props) {
        super(props);
        this.init();
    }

    init() {
        this.pageNotFoundText = StaticHelper.formatString(this.lang.NotFoundFormat, this.lang.Page);
    }

}

// client/src/app/not-found/not-found.component.ts
import { bounce } from 'ng-animate';
import { Component } from '@angular/core';
import { Constants } from 'src/shared/constants';
import { GlobalsService } from 'src/services/globals.service';
import { LanguageBase } from 'src/shared/language';
import { StaticHelper } from 'src/shared/static-helper';

@Component({
    selector: 'not-found-component',
    styleUrls: ['not-found.component.css'],
    template:
`<div class="body signupwrap">
    <h1 [innerHTML]="pageNotFoundText"></h1>
    <section class="error-container">
        <span>4</span>
        <span><span class="screen-reader-text">0</span></span>
        <span>4</span>
    </section>
    <div class="link-container">
        <a [routerLink]="constants.RoutePaths.Home" class="more-link" [innerHTML]="globals.lang.BackToHome"></a>
    </div>
</div>
`

})
export class NotFoundComponent {
    constants: Constants;
    pageNotFoundText: string;
    constructor(public globals: GlobalsService)
    {

    }

    ngOnInit() {
        this.constants = this.globals.constants;
        this.pageNotFoundText = StaticHelper.formatString(this.globals.lang.NotFoundFormat, this.globals.lang.Page);
    }

}
