// client/src/app/modules/funding/FundingComponent.tsx
import * as React from "react";
import DepositComponent from "./DepositComponent";
import { Switch, Route } from "react-router";
import { mdProps } from "../../../models/props";

const FundingComponent = (props) => {
  return (
    <Switch>
      <Route path={`${props.match.url}/deposit`} render={() => <DepositComponent {...props} />} />
    </Switch>
  );
}
  
export default FundingComponent;
// export default class FundingComponent extends BaseComponent {

//     render() {
//         this.initShorts();
//         return (
//             <div className="mainpage clearfix">
//                 <section className="tradingwrap  dashboad clearfix">
//                     <div className=" col-md-12">
//                         <ul className="nav nav-tabs">
//                             <li className="active"><a data-toggle="tab" href="#deposit">{this.lang.Deposit}</a></li>
//                             <li><a data-toggle="tab" href="#withdrawl">{this.lang.Withdrawl}</a></li>
//                         </ul>
//                         <div className="tab-content">
//                             <div id="deposit" className="tab-pane fade in active">
//                                 <DepositComponent {...this.props} />
//                             </div>
//                             <div id="withdrawl" className="tab-pane fade in">
//                             </div>
//                         </div>
//                     </div>
//                 </section>
//             </div>
//         );
//     }

//     constructor(props) {
//         super(props);
//         this.init();
//     }

//     init() {
//     }

// }

// client/src/modules/funding/funding.component.ts
import { Component } from '@angular/core';
import { Injectable } from '@angular/core';
import { Router } from '@angular/router';
import { LanguageBase } from 'src/shared/language';
import { GlobalsService } from 'src/services/globals.service';
import { Constants } from 'src/shared/constants';
import { SearchableDropdownSettings } from '../searchable-dropdown/searchable-dropdown-settings';
import { LoggerService } from 'src/services/logger.service';
import { HttpClientService } from 'src/services/http-client.service';
import { mdCallResponse } from 'src/models/call-response';
import { StaticHelper } from 'src/shared/static-helper';

@Component({
    selector: 'funding-root',
    templateUrl: './funding.component.html',
    styleUrls: []
})

@Injectable()
export class FundingComponent {

    lang: LanguageBase;
    constants: Constants;

    constructor(
        private router: Router,
        public globals: GlobalsService,
        private log: LoggerService,
        private http: HttpClientService
    ) {
    }

    ngOnInit() {
        this.lang = this.globals.lang;
        this.constants = Constants.Instance;
    }

}

<div class="mainpage clearfix">
    <!-- Trading Start -->
    <section class="tradingwrap  dashboad clearfix">
        <div class=" col-md-12">
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#deposit-tab">{{lang.Deposit}}</a></li>
                <li><a data-toggle="tab" href="#withdrawl-tab">{{lang.Withdrawl}}</a></li>
                <!-- <li><a data-toggle="tab" href="#eur-tab">Stop-Loss</a></li> -->
            </ul>
            <div class="tab-content">
                <div id="deposit-tab" class="tab-pane fade in active">
                    <funding-deposit></funding-deposit>
                </div>
                <div id="withdrawl-tab" class="tab-pane fade in">
                </div>
            </div>
        </div>
    </section>
</div>
